import { createHash } from 'node:crypto';
import { readFileSync } from 'node:fs';
import { locales, downloadPath } from './locales.mjs';
import { downloadCopy } from './download-copy.mjs';
import { renderCli } from './cli.mjs';
import { cliCopy } from './cli-copy.mjs';
import { brand, icon, esc, siteCopy, renderHeader, renderFooter } from './site.mjs';
const revision = createHash('sha256').update(readFileSync(new URL('./style.css',import.meta.url))).update(readFileSync(new URL('./download.css',import.meta.url))).update(readFileSync(new URL('./download.js',import.meta.url))).update(readFileSync(new URL('./cli.js',import.meta.url))).digest('hex').slice(0,12);

export function renderDownload(lang, releases, details) {
  const locale = locales.find(item => item.id === lang);
  if (!locale) throw Error('Unknown locale: ' + lang);
  const t = downloadCopy[lang], base = siteCopy(lang);
  const size = key => new Intl.NumberFormat(locale.tag,{maximumFractionDigits:1,minimumFractionDigits:1}).format(details[key].bytes / 1000000) + ' MB';
  const button = (key, label, primary=false) => typeof releases[key] === 'string' && releases[key].startsWith('https://')
    ? `<a class="button download-button ${primary?'button-primary':'button-outline'}" href="${esc(releases[key])}"><span>${label}<small>${size(key)} · ${key==='android'?'APK':key==='windows'?'EXE':'DMG'}</small></span>${icon('down')}</a>`
    : `<p class="download-pending">${t.soon}</p>`;
  const checksum = keys => `<details class="checksums"><summary>${t.checksum}</summary>${keys.map(key=>`<div><span>${key==='macArm64'?t.apple:key==='macIntel'?t.intel:details[key].version}</span><code>${details[key].sha256}</code></div>`).join('')}<a href="${esc(details[keys[0]].checksum)}">${t.checksumFile} ${icon('down')}</a></details>`;
  const badge = platform => `<span class="device-badge" data-device="${platform}" hidden>${t.recommended}</span>`;
  const date = new Intl.DateTimeFormat(locale.tag,{year:'numeric',month:'short',day:'numeric',timeZone:'UTC'}).format(new Date(details.date+'T00:00:00Z'));
  return `<!doctype html><html lang="${locale.tag}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#111215"><script>(()=>{let saved;try{saved=localStorage.getItem('kissopen-site-appearance')}catch{}const mode=saved==='light'||saved==='dark'?saved:matchMedia('(prefers-color-scheme: light)').matches?'light':'dark';document.documentElement.dataset.appearance=mode;document.querySelector('meta[name="theme-color"]').content=mode==='light'?'#f7f7fb':'#111215'})()</script><title>${t.title} — KissOpen</title><meta name="description" content="${esc(t.description)}"><link rel="canonical" href="https://kissopen.com${downloadPath(locale)}">${locales.map(item=>`<link rel="alternate" hreflang="${item.tag}" href="https://kissopen.com${downloadPath(item)}">`).join('')}<link rel="alternate" hreflang="x-default" href="https://kissopen.com/download/"><meta property="og:title" content="${t.title}"><meta property="og:description" content="${esc(t.description)}"><meta property="og:type" content="website"><meta property="og:url" content="https://kissopen.com${downloadPath(locale)}"><link rel="icon" href="/assets/favicon.ico"><link rel="stylesheet" href="/style.css?v=${revision}"><link rel="stylesheet" href="/download.css?v=${revision}"><script type="module" src="/download.js?v=${revision}"></script><script type="module" src="/cli.js?v=${revision}"></script></head><body class="download-page"><a class="skip" href="#main">${base.skip}</a><div class="page-frame">
${renderHeader(lang,releases,'download')}
<main id="main"><section class="hero download-intro"><div><p class="eyebrow"><span></span>${t.eyebrow}</p><h1>${t.title}</h1><p class="hero-description download-tagline">${t.intro}</p><p class="download-description">${t.description}</p></div><div class="release-stamp"><i class="live-dot"></i><span>${t.available}<small>${t.release} · <time datetime="${details.date}">${date}</time></small></span></div></section>
${renderCli(lang)}
<section class="download-grid" aria-label="${t.title}">
<article class="feature-card download-card" id="windows"><div class="platform-heading"><div class="platform-icon">${icon('monitor')}</div>${badge('windows')}</div><p class="platform-category">${t.desktop}</p><h2>Windows<span>v${details.windows.version}</span></h2><p class="platform-description">${t.windowsText}</p><div class="platform-downloads"><p class="platform-requirement">${t.winArch}</p>${button('windows',t.download+' Windows',true)}</div><p class="platform-note">${t.winNote}</p>${checksum(['windows'])}</article>
<article class="feature-card download-card" id="macos"><div class="platform-heading"><div class="platform-icon">${icon('monitor')}</div>${badge('macos')}</div><p class="platform-category">${t.desktop}</p><h2>macOS<span>v${details.macArm64.version}</span></h2><p class="platform-description">${t.macText}</p><div class="platform-downloads">${button('macArm64',t.apple)}${button('macIntel',t.intel)}</div><p class="platform-note">${t.macNote}</p>${checksum(['macArm64','macIntel'])}</article>
<article class="feature-card download-card" id="android"><div class="platform-heading"><div class="platform-icon">${icon('phone')}</div>${badge('android')}</div><p class="platform-category">${t.mobile}</p><h2>Android<span>v${details.android.version}</span></h2><p class="platform-description">${t.androidText}</p><div class="platform-downloads"><p class="platform-requirement">${t.androidArch}</p>${button('android',t.download+' APK',true)}</div><p class="platform-note">${t.androidNote}</p>${checksum(['android'])}</article>
</section><section class="other-platforms"><article class="feature-card web-download"><div class="platform-icon">${icon('globe')}</div><div><h2>${t.webTitle}</h2><p>${t.webText}</p></div><a class="underlink" href="https://app.kissopen.com/" target="_blank" rel="noopener noreferrer">${t.openWeb}${icon('arrow')}</a></article><article class="feature-card ios-download"><div class="platform-icon">${icon('phone')}</div><div><h2>${t.iosTitle}</h2><p>${t.iosText}</p></div><span class="pending-badge">${t.soon}</span></article></section>
<section class="start section download-guide"><div class="section-heading"><p class="eyebrow"><span></span>${base.startEyebrow}</p><h2>${t.guideTitle}</h2></div><ol class="quickstart">${t.steps.map((step,index)=>`<li><span>0${index+1}</span><div><h3>${step}</h3><p>${t.stepDetails[index]}</p></div></li>`).join('')}</ol></section></main>
${renderFooter(lang,releases,'download')}</div><script type="application/json" id="page-copy">${JSON.stringify({lightMode:base.lightMode,darkMode:base.darkMode,motionOn:base.motionOn,motionOff:base.motionOff,cliCopied:cliCopy[lang].copied,cliCopyFailed:cliCopy[lang].copyFailed}).replaceAll('<','\\u003c')}</script></body></html>`;
}
