export const downloadCopy = {
  en: {
    title:'Download KissOpen', intro:'Your workspace, on your devices.', description:'Run your Agent on your computer. Connect from your phone and keep working in the same workspace.', home:'Home', eyebrow:'KISSOPEN / DOWNLOADS', available:'Available now', recommended:'For your device', download:'Download', release:'Released', desktop:'Desktop', mobile:'Mobile', windowsText:'The desktop app with a bundled local Agent. Bring your own models, plugins and workspace.', macText:'The desktop app for Apple Silicon and Intel. Choose the installer for your Mac.', androidText:'Connect to your desktop Agent and continue conversations from your Android device.', winArch:'64-bit Windows · EXE installer', androidArch:'Android 7.0+ · ARM64 / ARMv7', apple:'Apple Silicon', intel:'Intel', winNote:'This Windows installer is not code-signed.', macNote:'Developer ID-signed and notarized by Apple.', androidNote:'Release-signed APK. Download and open the file on your Android device to install.', checksum:'SHA-256 checksums', checksumFile:'Download checksum file', webTitle:'Prefer the browser?', webText:'Open the Web client without installing an app.', openWeb:'Open Web client', iosTitle:'iPhone & iPad', iosText:'The iOS download is still being prepared.', soon:'Coming soon', guideTitle:'Start on your desktop. Continue on your phone.', steps:['Install the desktop app','Connect your models','Sign in on your phone'], stepDetails:['Sign in and start your local Agent.','Add a provider or your own API URL and key in settings.','Use the same account and keep your desktop Agent online.'], footer:'KissOpen · Open-source AI workspace', back:'Back to the project', theme:'Switch appearance', language:'Language'
  },
  zh: {
    title:'下载 KissOpen', intro:'在你的设备上，继续工作。', description:'Agent 在电脑上运行，手机连接同一个工作空间。选择你的设备，开始使用 KissOpen。', home:'首页', eyebrow:'KISSOPEN / 下载', available:'已开放下载', recommended:'适合你的设备', download:'下载', release:'发布日期', desktop:'桌面客户端', mobile:'移动客户端', windowsText:'内置本地 Agent，接入自己的模型，使用插件并管理工作空间。', macText:'支持 Apple 芯片与 Intel Mac，选择与你的电脑匹配的安装包。', androidText:'连接在线的桌面 Agent，在手机上继续对话、查看文件与处理任务。', winArch:'64 位 Windows · EXE 安装包', androidArch:'Android 7.0 及以上 · ARM64 / ARMv7', apple:'Apple 芯片', intel:'Intel 芯片', winNote:'此 Windows 安装包尚未进行代码签名。', macNote:'已通过 Developer ID 签名与 Apple 公证。', androidNote:'已使用发布密钥签名。在 Android 设备上下载并打开 APK 文件完成安装。', checksum:'SHA-256 校验值', checksumFile:'下载校验文件', webTitle:'也可以直接在浏览器中使用。', webText:'无需安装，打开 Web 客户端即可进入工作空间。', openWeb:'打开 Web 客户端', iosTitle:'iPhone 与 iPad', iosText:'iOS 版本公开下载仍在准备中。', soon:'即将开放', guideTitle:'从桌面开始，在手机上继续。', steps:['安装桌面客户端','接入你的模型','在手机上登录'], stepDetails:['登录账号，启动本地 Agent。','在设置中添加服务商，或填写自己的 API 地址和 Key。','使用同一账号，并让桌面 Agent 保持在线。'], footer:'KissOpen · 开源 AI 工作空间', back:'返回项目首页', theme:'切换显示模式', language:'语言'
  },
  'zh-tw': {
    title:'下載 KissOpen', intro:'在你的裝置上，繼續工作。', description:'Agent 在電腦上執行，手機連接同一個工作空間。選擇你的裝置，開始使用 KissOpen。', home:'首頁', eyebrow:'KISSOPEN / 下載', available:'已開放下載', recommended:'適合你的裝置', download:'下載', release:'發行日期', desktop:'桌面用戶端', mobile:'行動用戶端', windowsText:'內建本機 Agent，串接自己的模型，使用外掛並管理工作空間。', macText:'支援 Apple 晶片與 Intel Mac，選擇符合你電腦的安裝程式。', androidText:'連接在線的桌面 Agent，在手機上繼續對話、查看檔案與處理任務。', winArch:'64 位元 Windows · EXE 安裝程式', androidArch:'Android 7.0 以上 · ARM64 / ARMv7', apple:'Apple 晶片', intel:'Intel 晶片', winNote:'此 Windows 安裝程式尚未進行程式碼簽署。', macNote:'已通過 Developer ID 簽署與 Apple 公證。', androidNote:'已使用發行金鑰簽署。在 Android 裝置下載並開啟 APK 檔案完成安裝。', checksum:'SHA-256 校驗值', checksumFile:'下載校驗檔案', webTitle:'也能直接在瀏覽器中使用。', webText:'無需安裝，開啟 Web 用戶端即可進入工作空間。', openWeb:'開啟 Web 用戶端', iosTitle:'iPhone 與 iPad', iosText:'iOS 版本公開下載仍在準備中。', soon:'即將開放', guideTitle:'從桌面開始，在手機上繼續。', steps:['安裝桌面用戶端','串接你的模型','在手機上登入'], stepDetails:['登入帳號，啟動本機 Agent。','在設定中新增服務商，或輸入自己的 API 網址和 Key。','使用同一帳號，並讓桌面 Agent 保持在線。'], footer:'KissOpen · 開源 AI 工作空間', back:'返回專案首頁', theme:'切換顯示模式', language:'語言'
  },
  ja: {
    title:'KissOpen をダウンロード', intro:'どのデバイスでも、作業の続きを。', description:'Agent はパソコンで実行。スマートフォンから同じワークスペースに接続できます。', home:'ホーム', eyebrow:'KISSOPEN / ダウンロード', available:'公開中', recommended:'このデバイスに対応', download:'ダウンロード', release:'公開日', desktop:'デスクトップ', mobile:'モバイル', windowsText:'ローカル Agent を同梱。自分のモデルやプラグインでワークスペースを管理できます。', macText:'Apple シリコンと Intel Mac に対応。お使いの Mac に合うインストーラーを選んでください。', androidText:'オンラインのデスクトップ Agent に接続し、スマートフォンで会話や作業を続けられます。', winArch:'64 ビット Windows · EXE', androidArch:'Android 7.0 以降 · ARM64 / ARMv7', apple:'Apple シリコン', intel:'Intel', winNote:'この Windows インストーラーにはコード署名がありません。', macNote:'Developer ID 署名・Apple 公証済みです。', androidNote:'リリース鍵で署名済みの APK です。Android 端末でダウンロードしたファイルを開いてインストールしてください。', checksum:'SHA-256 チェックサム', checksumFile:'チェックサムをダウンロード', webTitle:'ブラウザーでも使えます。', webText:'インストールせずに Web クライアントを開けます。', openWeb:'Web クライアントを開く', iosTitle:'iPhone・iPad', iosText:'iOS 版の一般公開は準備中です。', soon:'準備中', guideTitle:'パソコンで始めて、スマートフォンで続ける。', steps:['デスクトップアプリをインストール','自分のモデルを接続','スマートフォンでログイン'], stepDetails:['ログインしてローカル Agent を起動します。','設定でプロバイダーや API URL とキーを追加します。','同じアカウントを使い、デスクトップ Agent をオンラインに保ちます。'], footer:'KissOpen · オープンソースの AI ワークスペース', back:'プロジェクトのホームへ', theme:'表示モードを切り替え', language:'言語'
  },
  ko: {
    title:'KissOpen 다운로드', intro:'어떤 기기에서든 작업을 이어가세요.', description:'컴퓨터에서 Agent를 실행하고 휴대전화로 같은 작업 공간에 연결하세요.', home:'홈', eyebrow:'KISSOPEN / 다운로드', available:'다운로드 가능', recommended:'이 기기에 적합', download:'다운로드', release:'출시일', desktop:'데스크톱', mobile:'모바일', windowsText:'로컬 Agent가 포함되어 있습니다. 자신의 모델과 플러그인으로 작업 공간을 관리하세요.', macText:'Apple Silicon 및 Intel Mac을 지원합니다. 사용하는 Mac에 맞는 설치 파일을 선택하세요.', androidText:'온라인 데스크톱 Agent에 연결하여 휴대전화에서 대화와 작업을 이어가세요.', winArch:'64비트 Windows · EXE', androidArch:'Android 7.0 이상 · ARM64 / ARMv7', apple:'Apple Silicon', intel:'Intel', winNote:'이 Windows 설치 파일에는 코드 서명이 없습니다.', macNote:'Developer ID 서명과 Apple 공증을 완료했습니다.', androidNote:'배포 키로 서명된 APK입니다. Android 기기에서 다운로드한 파일을 열어 설치하세요.', checksum:'SHA-256 체크섬', checksumFile:'체크섬 파일 다운로드', webTitle:'브라우저에서도 사용할 수 있습니다.', webText:'설치 없이 웹 클라이언트를 여세요.', openWeb:'웹 클라이언트 열기', iosTitle:'iPhone 및 iPad', iosText:'iOS 공개 다운로드는 준비 중입니다.', soon:'준비 중', guideTitle:'컴퓨터에서 시작하고 휴대전화에서 이어가세요.', steps:['데스크톱 앱 설치','자신의 모델 연결','휴대전화에서 로그인'], stepDetails:['로그인하고 로컬 Agent를 시작하세요.','설정에서 서비스 또는 자신의 API URL과 키를 추가하세요.','같은 계정을 사용하고 데스크톱 Agent를 온라인으로 유지하세요.'], footer:'KissOpen · 오픈 소스 AI 작업 공간', back:'프로젝트 홈으로', theme:'화면 모드 전환', language:'언어'
  },
  ru: {
    title:'Скачать KissOpen', intro:'Продолжайте работу на своих устройствах.', description:'Запустите Agent на компьютере и подключайтесь к тому же рабочему пространству с телефона.', home:'Главная', eyebrow:'KISSOPEN / ЗАГРУЗКИ', available:'Доступно', recommended:'Для вашего устройства', download:'Скачать', release:'Дата выпуска', desktop:'Для компьютера', mobile:'Для телефона', windowsText:'Приложение со встроенным локальным Agent. Подключайте свои модели и плагины, управляйте рабочим пространством.', macText:'Для Apple Silicon и Intel Mac. Выберите установщик для своего компьютера.', androidText:'Подключайтесь к Agent на компьютере и продолжайте диалоги и работу с телефона.', winArch:'64-битная Windows · EXE', androidArch:'Android 7.0+ · ARM64 / ARMv7', apple:'Apple Silicon', intel:'Intel', winNote:'Установщик Windows не имеет подписи кода.', macNote:'Подписано Developer ID и заверено Apple.', androidNote:'APK подписан ключом выпуска. Скачайте и откройте файл на устройстве Android для установки.', checksum:'Контрольные суммы SHA-256', checksumFile:'Скачать контрольные суммы', webTitle:'Можно работать и в браузере.', webText:'Откройте веб-клиент без установки приложения.', openWeb:'Открыть веб-клиент', iosTitle:'iPhone и iPad', iosText:'Публичная версия iOS ещё готовится.', soon:'Скоро', guideTitle:'Начните на компьютере. Продолжайте с телефона.', steps:['Установите приложение','Подключите свои модели','Войдите с телефона'], stepDetails:['Войдите в аккаунт и запустите локальный Agent.','Добавьте провайдера или свой URL API и ключ в настройках.','Используйте тот же аккаунт, оставив Agent на компьютере в сети.'], footer:'KissOpen · AI-пространство с открытым кодом', back:'На главную проекта', theme:'Сменить оформление', language:'Язык'
  }
};
