export const locales = [
  { id: 'en', tag: 'en', og: 'en_US', path: '/', label: 'English' },
  { id: 'zh', tag: 'zh-CN', og: 'zh_CN', path: '/zh-cn/', label: '简体中文' },
  { id: 'zh-tw', tag: 'zh-TW', og: 'zh_TW', path: '/zh-tw/', label: '繁體中文' },
  { id: 'ja', tag: 'ja', og: 'ja_JP', path: '/ja/', label: '日本語' },
  { id: 'ko', tag: 'ko', og: 'ko_KR', path: '/ko/', label: '한국어' },
  { id: 'ru', tag: 'ru', og: 'ru_RU', path: '/ru/', label: 'Русский' },
];

// Keep previously shared English URLs working, with the root as canonical.
export function localeForPath(pathname) {
  if (['/en', '/en/', '/en/index.html'].includes(pathname)) return locales[0];
  return locales.find(locale => [locale.path, locale.path + 'index.html', locale.path.slice(0, -1)].includes(pathname));
}

export function downloadPath(locale) { return locale.path + 'download/'; }
export function downloadLocaleForPath(pathname) {
  if (['/en/download', '/en/download/', '/en/download/index.html'].includes(pathname)) return locales[0];
  return locales.find(locale => [downloadPath(locale), downloadPath(locale) + 'index.html', downloadPath(locale).slice(0, -1)].includes(pathname));
}

const technical = { windows: 'Windows · x64', file: 'upgrade-notes.md', fileType: '12 KB · Markdown', ios: 'iPhone / iPad', android: 'Android' };

export const translations = {
  'zh-tw': {
    ...technical,
    title:'KissOpen — 開源 AI 工作空間', description:'KissOpen 是一個開源 AI 工作空間專案，由桌面與行動版用戶端、本機 Agent 和可自行部署的伺服器組成。串接自己的模型，使用外掛、佈景主題和本機排程任務。',
    nav:['專案','功能','本機執行'], github:'GitHub', download:'取得 KissOpen', skip:'跳至主要內容', menu:'開啟導覽',
    eyebrow:'KISSOPEN / 開源專案', hero:['開源 AI 工作空間。','本機執行，跨裝置連線。'], intro:'Agent 在你的電腦上執行，連接你設定的模型。桌面與手機存取同一個工作空間，程式碼也可以自己修改。', note:'桌面與行動版用戶端 / 本機 Agent / 可自行部署的伺服器', watch:'觀看跨裝置示範', heroAction:'瞭解如何執行',
    demoLabel:'互動示範', demoTitle:'桌面與手機如何連接同一個 Agent。', desktop:'桌面', mobile:'手機', demoCaption:'示範內容 · 手機連上在線的 Agent 後繼續工作', pause:'暫停示範', play:'播放示範', replay:'重新播放',
    work:'工作', library:'資料庫', plugins:'外掛', tasks:'排程任務', themes:'佈景主題', projects:'專案', project:'專案文件', conversation:'版本更新', user:'閱讀專案的更新日誌，整理一份升級說明。', agentReply:'我會讀取更新日誌、檢查相容性變更，並儲存至專案目錄。',
    steps:['讀取更新日誌','檢查相容性變更','儲存 upgrade-notes.md'], connected:'Agent 已連線', browser:'瀏覽器', sourceTitle:'專案更新日誌。', sourceSub:'新功能、相容性變更與遷移說明。', sourceLabels:['新功能','相容性變更','遷移說明'], input:'接下來一起做什麼？',
    phoneConnected:'桌面 Agent 在線', phoneUser:'再加一頁摘要。', phoneReply:'正在更新升級說明…', phoneDone:'已加入摘要，桌面同步完成。', phoneInput:'傳訊息給 KissOpen…',
    stageNames:['桌面發起','Agent 執行','手機接力','結果同步'], stageTitles:['在桌面提交任務。','本機 Agent 執行。','手機連上同一段對話。','工作空間中的檔案已更新。'], stageDescriptions:['在桌面發起任務，讓對話、檔案和工具留在同一個工作空間。','讀取更新日誌、整理變更，將升級說明儲存至專案目錄。','在手機開啟同一段對話，查看文件，再補充一句需求。','更新後的檔案回到同一個工作空間，接著往下做。'],
    shared:['同一個 Agent','同一段對話','同一個工作空間'], featureEyebrow:'功能 / CAPABILITIES', featureTitle:'模型、介面和工具，都能自行設定。', featureIntro:'這些是專案目前提供的功能。下方控制項可供試用，不會更改實際設定。',
    modelsTitle:'自訂模型 API', modelsText:'填入 API 網址和 Key，取得模型清單，多選或全選，自由組合。', provider:'服務商', providerName:'我的模型服務', api:'API 網址', selected:'已選擇 {n} 個模型', all:'全選模型', modelDemo:'模型選擇示範',
    themeTitle:'自訂佈景主題', themeText:'切換配色、換上背景，或用一句話，讓 AI 為你製作佈景主題。', themeNames:['暮紫','青川','暖陽','墨'], createTheme:'試試其他主題', themePrompt:'「安靜一點的深色，帶一點紫。」', themePreview:'佈景主題預覽',
    pluginTitle:'本機外掛', pluginText:'在本機 Agent 安裝、啟用、停用和移除外掛，擴充瀏覽器、文件與開發工具。', pluginNames:['瀏覽器工具','文件工具','開發工具'], pluginCount:'已啟用 {n} 項功能', togglePlugin:'切換',
    taskTitle:'本機排程任務', taskText:'在對話裡說清楚要做什麼、何時執行，交給本機 Agent 排程處理。', taskName:'檢查專案更新', frequencies:['每天','每週','每小時'], times:['每天 · 09:00','每週一 · 09:00','每小時 · 整點'], nextRuns:['下次執行 · 明天 09:00','下次執行 · 週一 09:00','下次執行 · 下一個整點'], run:'立即執行', running:'正在檢查更新…', ran:'已產生更新紀錄', taskHint:'Agent 在線時執行',
    startEyebrow:'執行 / GET STARTED', startTitle:'先在自己的電腦上執行。', startText:'模型 API 需要自行設定；使用遠端 API 時，請求會傳送至對應服務商。跨裝置存取時，本機 Agent 需要保持在線。', guide:'快速上手', guideSteps:['啟動桌面 Agent','串接你的模型','連接手機，繼續工作'], guideDetails:['登入桌面用戶端並啟動本機 Agent。','在設定中加入服務商，或填入自訂 API 網址和 Key。','讓桌面 Agent 保持在線，在手機使用同一個工作空間繼續對話。'],
    openEyebrow:'架構 / OPEN SOURCE', openTitle:'用戶端、Agent、伺服器，分開維護。', openIntro:'桌面負責執行 Agent；手機透過伺服器連接它，不會另外啟動雲端 Agent。', parts:['用戶端','本機 Agent','伺服器'], partDetails:['桌面與行動版介面：對話、檔案、模型設定和佈景主題。','在電腦上執行工具、管理工作空間，並儲存與執行排程任務。','提供帳號和裝置連線服務，可獨立部署；不負責雲端模型推論。'], contributeTitle:'不只是使用，也能參與。', contributeText:'重現問題、補充文件、製作佈景主題、開發外掛，或直接修改程式碼。透過 GitHub 提交 Issue 和 Pull Request，一起完善 KissOpen。', sourceStatus:'公開儲存庫：kissopen/kissopen。', footer:'KissOpen · 開源 AI 工作空間', motion:'動態效果', motionOn:'開啟', motionOff:'關閉',
    getTitle:'取得 KissOpen', getDesc:'選擇你要使用的裝置。', macArm:'macOS · Apple 晶片', macIntel:'macOS · Intel', soon:'即將開放公開下載', distribution:'macOS 0.3.2 與 Windows 0.3.0、Android 0.2.29 已開放下載。macOS 已簽署並通過 Apple 公證；Windows 安裝程式未做程式碼簽署；Android APK 使用專案發行金鑰簽署，支援 Android 7.0 以上的 ARM 裝置。iOS 下載仍在準備。', web:'開啟目前的 Web 用戶端 ↗', close:'關閉', keyNote:'這是介面示範，不需要輸入真實金鑰。',
    language:'語言', mainNavigation:'主要導覽', mobileNavigation:'行動導覽', openApp:'開啟用戶端', appearanceToggle:'切換淺色／深色模式', darkMode:'切換至深色模式', lightMode:'切換至淺色模式', demoStages:'示範步驟', myModel:'我的模型', changelog:'更新日誌', docs:'文件', projectNotes:'專案筆記', extensions:'外掛 / 擴充功能',
  },
  ja: {
    ...technical,
    title:'KissOpen — オープンソースの AI ワークスペース', description:'デスクトップ・モバイルアプリ、ローカル Agent、セルフホスト可能なサーバーからなるオープンソースの AI ワークスペース。自分のモデル、プラグイン、テーマ、定期タスクを使えます。',
    nav:['プロジェクト','機能','ローカルで実行'], github:'GitHub', download:'KissOpen を入手', skip:'本文へスキップ', menu:'メニューを開く',
    eyebrow:'KISSOPEN / オープンソース', hero:['オープンソースの','AI ワークスペース。'], intro:'自分のパソコンで動く Agent に、自分のモデルを接続。デスクトップとスマートフォンで同じワークスペースを使い、コードも自由に変更できます。', note:'デスクトップ・モバイルアプリ / ローカル Agent / セルフホスト可能なサーバー', watch:'デバイス連携のデモを見る', heroAction:'実行方法を見る',
    demoLabel:'インタラクティブデモ', demoTitle:'デスクトップとスマートフォンで、同じ Agent に接続。', desktop:'デスクトップ', mobile:'スマートフォン', demoCaption:'操作イメージ · Agent がオンラインなら、スマートフォンでも続けられます', pause:'デモを一時停止', play:'デモを再生', replay:'デモを最初から再生',
    work:'作業', library:'ライブラリ', plugins:'プラグイン', tasks:'定期タスク', themes:'テーマ', projects:'プロジェクト', project:'プロジェクト文書', conversation:'リリースノート', user:'変更履歴を読んで、アップグレードガイドをまとめて。', agentReply:'変更履歴と互換性への影響を確認し、ガイドをプロジェクトに保存します。',
    steps:['変更履歴を読む','互換性の変更を確認','upgrade-notes.md を保存'], connected:'Agent に接続済み', browser:'ブラウザー', sourceTitle:'プロジェクトの変更履歴。', sourceSub:'新機能、互換性の変更、移行手順。', sourceLabels:['新機能','互換性','移行手順'], input:'次は何をしましょう？',
    phoneConnected:'デスクトップ Agent がオンライン', phoneUser:'1 ページの要約も追加して。', phoneReply:'ガイドを更新中…', phoneDone:'要約を追加しました。デスクトップにも反映済みです。', phoneInput:'KissOpen にメッセージ…',
    stageNames:['デスクトップで開始','Agent が実行','スマホで続ける','結果を同期'], stageTitles:['デスクトップからタスクを送信。','ローカル Agent が実行。','スマートフォンで同じ会話に接続。','ワークスペースのファイルを更新。'], stageDescriptions:['デスクトップで作業を開始。会話、ファイル、ツールを一つのワークスペースに。','変更履歴を読み、変更点を確認してガイドをプロジェクトに保存します。','スマートフォンで同じ会話を開き、ガイドを確認して依頼を追加。','更新されたファイルは同じワークスペースに。そこから作業を続けられます。'],
    shared:['同じ Agent','同じ会話','同じワークスペース'], featureEyebrow:'機能 / CAPABILITIES', featureTitle:'モデルも、画面も、ツールも自分好みに。', featureIntro:'現在の機能を下の操作で試せます。実際の設定は変更されません。',
    modelsTitle:'カスタムモデル API', modelsText:'API URL とキーを設定してモデル一覧を取得。複数選択も、すべて選択もできます。', provider:'プロバイダー', providerName:'自分のモデルサービス', api:'API URL', selected:'{n} 個のモデルを選択', all:'すべて選択', modelDemo:'モデル選択のデモ',
    themeTitle:'カスタムテーマ', themeText:'配色や背景を変更。イメージを言葉で伝えて、AI にテーマを作ってもらうこともできます。', themeNames:['夕暮れ','川','琥珀','モノクロ'], createTheme:'別のテーマを試す', themePrompt:'「落ち着いたダーク系で、紫を少し。」', themePreview:'テーマのプレビュー',
    pluginTitle:'ローカルプラグイン', pluginText:'ローカル Agent にプラグインをインストール、有効化、無効化、削除。ブラウザー、文書、開発ツールを拡張できます。', pluginNames:['ブラウザーツール','文書ツール','開発ツール'], pluginCount:'{n} 個の機能が有効', togglePlugin:'切り替え',
    taskTitle:'ローカル定期タスク', taskText:'チャットで内容と実行日時を伝えるだけ。ローカル Agent が保存し、予定どおりに実行します。', taskName:'プロジェクトの更新を確認', frequencies:['毎日','毎週','毎時'], times:['毎日 · 09:00','毎週月曜日 · 09:00','毎時 · 00 分'], nextRuns:['次回 · 明日 09:00','次回 · 月曜日 09:00','次回 · 次の正時'], run:'今すぐ実行', running:'更新を確認中…', ran:'更新記録を保存しました', taskHint:'Agent がオンラインの間に実行',
    startEyebrow:'ローカルで実行', startTitle:'まずは自分のパソコンで。', startText:'モデル API は自分で設定します。外部 API を使う場合、リクエストはそのプロバイダーに送信されます。別のデバイスから使うには、ローカル Agent をオンラインにしておいてください。', guide:'クイックスタート', guideSteps:['デスクトップ Agent を起動','自分のモデルを接続','スマートフォンで続きを'], guideDetails:['デスクトップアプリにログインし、ローカル Agent を起動します。','設定でプロバイダーを追加するか、カスタム API URL とキーを入力します。','デスクトップ Agent をオンラインに保ち、スマートフォンで同じワークスペースを使います。'],
    openEyebrow:'オープンソース / 構成', openTitle:'アプリ、Agent、サーバーを個別に管理。', openIntro:'Agent はデスクトップで動きます。スマートフォンはサーバー経由で接続し、別のクラウド Agent は起動しません。', parts:['クライアント','ローカル Agent','サーバー'], partDetails:['会話、ファイル、モデル設定、テーマを扱うデスクトップ・モバイル画面。','パソコン上でツールを実行し、ワークスペースと定期タスクを管理します。','アカウントとデバイスの接続を提供。単独でデプロイでき、クラウドでのモデル推論は行いません。'], contributeTitle:'使うだけでなく、一緒に作る。', contributeText:'不具合の再現、ドキュメントの改善、テーマやプラグインの作成、コードの変更。GitHub の Issue と Pull Request で開発に参加できます。', sourceStatus:'公開リポジトリ：kissopen/kissopen。', footer:'KissOpen · オープンソースの AI ワークスペース', motion:'アニメーション', motionOn:'オン', motionOff:'オフ',
    getTitle:'KissOpen を入手', getDesc:'使用するデバイスを選んでください。', macArm:'macOS · Apple シリコン', macIntel:'macOS · Intel', soon:'一般公開を準備中', distribution:'macOS 0.3.2・Windows 0.3.0 と Android 0.2.29 を公開中です。macOS は署名・Apple 公証済み、Windows インストーラーはコード署名なしです。Android APK はプロジェクトのリリース鍵で署名済みで、Android 7.0 以降の ARM 端末に対応します。iOS は準備中です。', web:'現在の Web クライアントを開く ↗', close:'閉じる', keyNote:'操作デモです。実際の API キーは不要です。',
    language:'言語', mainNavigation:'メインナビゲーション', mobileNavigation:'モバイルナビゲーション', openApp:'アプリを開く', appearanceToggle:'ライト／ダークモードを切り替え', darkMode:'ダークモードに切り替え', lightMode:'ライトモードに切り替え', demoStages:'デモの手順', myModel:'自分のモデル', changelog:'変更履歴', docs:'ドキュメント', projectNotes:'プロジェクトノート', extensions:'プラグイン / 拡張機能',
  },
  ko: {
    ...technical,
    title:'KissOpen — 오픈 소스 AI 워크스페이스', description:'데스크톱·모바일 앱, 로컬 Agent, 직접 호스팅할 수 있는 서버로 구성된 오픈 소스 AI 워크스페이스. 원하는 모델, 플러그인, 테마, 로컬 예약 작업을 사용하세요.',
    nav:['프로젝트','기능','로컬 실행'], github:'GitHub', download:'KissOpen 다운로드', skip:'본문으로 건너뛰기', menu:'메뉴 열기',
    eyebrow:'KISSOPEN / 오픈 소스', hero:['오픈 소스','AI 워크스페이스.'], intro:'내 컴퓨터에서 실행되는 Agent에 내 모델을 연결하세요. 데스크톱과 휴대폰에서 같은 워크스페이스를 사용하고, 코드도 직접 수정할 수 있습니다.', note:'데스크톱·모바일 앱 / 로컬 Agent / 직접 호스팅 가능한 서버', watch:'기기 간 연결 데모 보기', heroAction:'실행 방법 알아보기',
    demoLabel:'인터랙티브 데모', demoTitle:'데스크톱과 휴대폰에서 같은 Agent에 연결합니다.', desktop:'데스크톱', mobile:'휴대폰', demoCaption:'사용 예시 · Agent가 온라인이면 휴대폰에서도 작업을 이어갈 수 있습니다', pause:'데모 일시 정지', play:'데모 재생', replay:'데모 다시 재생',
    work:'작업', library:'자료실', plugins:'플러그인', tasks:'예약 작업', themes:'테마', projects:'프로젝트', project:'프로젝트 문서', conversation:'릴리스 노트', user:'변경 기록을 읽고 업그레이드 안내서를 작성해 줘.', agentReply:'변경 기록과 호환성 변경 사항을 확인하고 안내서를 프로젝트에 저장하겠습니다.',
    steps:['변경 기록 읽기','호환성 변경 확인','upgrade-notes.md 저장'], connected:'Agent 연결됨', browser:'브라우저', sourceTitle:'프로젝트 변경 기록.', sourceSub:'새 기능, 호환성 변경 및 마이그레이션 안내.', sourceLabels:['새 기능','호환성','마이그레이션'], input:'다음에는 무엇을 할까요?',
    phoneConnected:'데스크톱 Agent 온라인', phoneUser:'한 페이지 요약도 추가해 줘.', phoneReply:'안내서 업데이트 중…', phoneDone:'요약을 추가했습니다. 데스크톱에도 반영됐습니다.', phoneInput:'KissOpen에 메시지 보내기…',
    stageNames:['데스크톱에서 시작','Agent 실행','휴대폰으로 이어서','결과 동기화'], stageTitles:['데스크톱에서 작업을 보냅니다.','로컬 Agent가 실행합니다.','휴대폰에서 같은 대화에 연결합니다.','워크스페이스의 파일을 업데이트합니다.'], stageDescriptions:['데스크톱에서 작업을 시작하고 대화, 파일, 도구를 한 워크스페이스에서 관리합니다.','변경 기록을 읽고 변경 사항을 검토한 뒤 안내서를 프로젝트에 저장합니다.','휴대폰에서 같은 대화를 열고 안내서를 확인한 뒤 요청을 추가합니다.','업데이트한 파일이 같은 워크스페이스에 저장됩니다. 그대로 작업을 이어가세요.'],
    shared:['같은 Agent','같은 대화','같은 워크스페이스'], featureEyebrow:'기능 / CAPABILITIES', featureTitle:'모델, 인터페이스, 도구를 내 방식대로.', featureIntro:'현재 지원하는 기능을 아래에서 체험해 보세요. 실제 설정은 변경되지 않습니다.',
    modelsTitle:'사용자 지정 모델 API', modelsText:'API URL과 키를 입력해 모델 목록을 불러오세요. 여러 모델을 선택하거나 모두 선택할 수 있습니다.', provider:'제공업체', providerName:'내 모델 서비스', api:'API URL', selected:'모델 {n}개 선택됨', all:'모두 선택', modelDemo:'모델 선택 데모',
    themeTitle:'사용자 지정 테마', themeText:'색상과 배경을 바꾸거나 원하는 분위기를 설명하면 AI가 테마를 만들어 줍니다.', themeNames:['황혼','강','호박빛','흑백'], createTheme:'다른 테마 사용해 보기', themePrompt:'“차분한 어두운 색에 보라색을 조금.”', themePreview:'테마 미리 보기',
    pluginTitle:'로컬 플러그인', pluginText:'로컬 Agent에 플러그인을 설치, 활성화, 비활성화, 제거하여 브라우저, 문서, 개발 도구를 확장하세요.', pluginNames:['브라우저 도구','문서 도구','개발 도구'], pluginCount:'기능 {n}개 활성화됨', togglePlugin:'전환',
    taskTitle:'로컬 예약 작업', taskText:'채팅에서 할 일과 실행 시간을 알려 주세요. 로컬 Agent가 작업을 저장하고 예약대로 실행합니다.', taskName:'프로젝트 업데이트 확인', frequencies:['매일','매주','매시간'], times:['매일 · 09:00','매주 월요일 · 09:00','매시간 · 정각'], nextRuns:['다음 실행 · 내일 09:00','다음 실행 · 월요일 09:00','다음 실행 · 다음 정각'], run:'지금 실행', running:'업데이트 확인 중…', ran:'업데이트 기록 저장 완료', taskHint:'Agent가 온라인일 때 실행',
    startEyebrow:'로컬 실행', startTitle:'내 컴퓨터에서 시작하세요.', startText:'모델 API는 직접 설정합니다. 외부 API를 사용하면 해당 제공업체로 요청이 전송됩니다. 다른 기기에서 접속하려면 로컬 Agent를 온라인으로 유지하세요.', guide:'빠른 시작', guideSteps:['데스크톱 Agent 시작','내 모델 연결','휴대폰에서 이어서 작업'], guideDetails:['데스크톱 앱에 로그인하고 로컬 Agent를 시작하세요.','설정에서 제공업체를 추가하거나 사용자 지정 API URL과 키를 입력하세요.','데스크톱 Agent를 온라인으로 유지하고 휴대폰에서 같은 워크스페이스를 사용하세요.'],
    openEyebrow:'오픈 소스 / 구조', openTitle:'클라이언트, Agent, 서버를 독립적으로 관리.', openIntro:'Agent는 데스크톱에서 실행됩니다. 휴대폰은 서버를 통해 연결하며 별도의 클라우드 Agent를 실행하지 않습니다.', parts:['클라이언트','로컬 Agent','서버'], partDetails:['대화, 파일, 모델 설정, 테마를 위한 데스크톱·모바일 인터페이스.','내 컴퓨터에서 도구를 실행하고 워크스페이스와 예약 작업을 관리합니다.','계정과 기기 연결 서비스를 제공합니다. 독립적으로 배포할 수 있으며 클라우드 모델 추론은 하지 않습니다.'], contributeTitle:'사용하고, 함께 만들어 가세요.', contributeText:'버그 재현, 문서 개선, 테마와 플러그인 제작, 코드 수정까지. GitHub에서 이슈와 풀 리퀘스트로 개발에 참여하세요.', sourceStatus:'공개 저장소: kissopen/kissopen.', footer:'KissOpen · 오픈 소스 AI 워크스페이스', motion:'애니메이션', motionOn:'켜짐', motionOff:'꺼짐',
    getTitle:'KissOpen 다운로드', getDesc:'사용할 기기를 선택하세요.', macArm:'macOS · Apple Silicon', macIntel:'macOS · Intel', soon:'공개 다운로드 준비 중', distribution:'macOS 0.3.2 및 Windows 0.3.0, Android 0.2.29을 다운로드할 수 있습니다. macOS는 서명과 Apple 공증을 완료했으며 Windows 설치 파일은 코드 서명이 없습니다. Android APK는 프로젝트 배포 키로 서명되었으며 Android 7.0 이상 ARM 기기를 지원합니다. iOS 다운로드는 준비 중입니다.', web:'현재 웹 클라이언트 열기 ↗', close:'닫기', keyNote:'인터랙티브 데모입니다. 실제 API 키는 필요하지 않습니다.',
    language:'언어', mainNavigation:'주 메뉴', mobileNavigation:'모바일 메뉴', openApp:'앱 열기', appearanceToggle:'라이트/다크 모드 전환', darkMode:'다크 모드로 전환', lightMode:'라이트 모드로 전환', demoStages:'데모 단계', myModel:'내 모델', changelog:'변경 기록', docs:'문서', projectNotes:'프로젝트 노트', extensions:'플러그인 / 확장 기능',
  },
  ru: {
    ...technical,
    title:'KissOpen — AI-пространство с открытым кодом', description:'AI-пространство с открытым кодом: приложения для компьютера и телефона, локальный Agent и сервер для самостоятельного размещения. Свои модели, плагины, темы и задачи по расписанию.',
    nav:['Проект','Возможности','Локальный запуск'], github:'GitHub', download:'Скачать KissOpen', skip:'Перейти к содержимому', menu:'Открыть меню',
    eyebrow:'KISSOPEN / ОТКРЫТЫЙ КОД', hero:['Открытый код.','Ваше AI-пространство.'], intro:'Agent работает на вашем компьютере и подключается к вашим моделям. Одно рабочее пространство на компьютере и телефоне. Код можно менять под себя.', note:'Приложения для компьютера и телефона / Локальный Agent / Собственный сервер', watch:'Демо работы на двух устройствах', heroAction:'Как запустить',
    demoLabel:'ИНТЕРАКТИВНОЕ ДЕМО', demoTitle:'Компьютер и телефон подключены к одному Agent.', desktop:'Компьютер', mobile:'Телефон', demoCaption:'Демонстрация · Продолжайте с телефона, пока ваш Agent в сети', pause:'Приостановить демо', play:'Воспроизвести демо', replay:'Начать демо заново',
    work:'Работа', library:'Библиотека', plugins:'Плагины', tasks:'Расписание', themes:'Темы', projects:'Проекты', project:'Документы проекта', conversation:'Заметки к выпуску', user:'Прочитай журнал изменений и подготовь инструкцию по обновлению.', agentReply:'Изучу журнал, проверю изменения совместимости и сохраню инструкцию в проекте.',
    steps:['Прочитать журнал изменений','Проверить совместимость','Сохранить upgrade-notes.md'], connected:'Agent подключён', browser:'Браузер', sourceTitle:'Журнал изменений проекта.', sourceSub:'Новые функции, совместимость и инструкции по миграции.', sourceLabels:['Новые функции','Совместимость','Миграция'], input:'Над чем поработаем дальше?',
    phoneConnected:'Agent на компьютере в сети', phoneUser:'Добавь краткое резюме на одну страницу.', phoneReply:'Обновляю инструкцию…', phoneDone:'Резюме добавлено. Изменения доступны на компьютере.', phoneInput:'Сообщение KissOpen…',
    stageNames:['Начало на компьютере','Agent выполняет','Продолжение с телефона','Синхронизация'], stageTitles:['Отправьте задачу с компьютера.','Локальный Agent выполняет её.','Откройте тот же диалог на телефоне.','Файлы в рабочем пространстве обновлены.'], stageDescriptions:['Начните на компьютере: диалог, файлы и инструменты находятся в одном рабочем пространстве.','Agent читает журнал, изучает изменения и сохраняет инструкцию в проекте.','Откройте тот же диалог на телефоне, прочитайте инструкцию и добавьте запрос.','Обновлённый файл остаётся в том же пространстве. Продолжайте работу с ним.'],
    shared:['Один Agent','Один диалог','Одно пространство'], featureEyebrow:'ВОЗМОЖНОСТИ', featureTitle:'Настраивайте модели, интерфейс и инструменты.', featureIntro:'Возможности проекта на сегодня. Попробуйте элементы ниже — реальные настройки не изменятся.',
    modelsTitle:'Свои API моделей', modelsText:'Укажите URL API и ключ, загрузите список моделей и выберите нужные — одну, несколько или все.', provider:'Провайдер', providerName:'Мой сервис моделей', api:'URL API', selected:'Выбрано моделей: {n}', all:'Выбрать все', modelDemo:'Демо выбора моделей',
    themeTitle:'Свои темы', themeText:'Меняйте цвета и фон или опишите тему словами, чтобы AI создал её для вас.', themeNames:['Сумерки','Река','Янтарь','Моно'], createTheme:'Попробовать другую тему', themePrompt:'«Спокойная тёмная тема с оттенком фиолетового».', themePreview:'Предпросмотр темы',
    pluginTitle:'Локальные плагины', pluginText:'Устанавливайте, включайте, отключайте и удаляйте плагины в локальном Agent: браузер, документы и инструменты разработки.', pluginNames:['Инструменты браузера','Инструменты документов','Инструменты разработки'], pluginCount:'Включено функций: {n}', togglePlugin:'Переключить',
    taskTitle:'Локальные задачи по расписанию', taskText:'Опишите в чате, что и когда нужно сделать. Локальный Agent сохранит задачу и выполнит её по расписанию.', taskName:'Проверить обновления проекта', frequencies:['Ежедневно','Еженедельно','Ежечасно'], times:['Каждый день · 09:00','Каждый понедельник · 09:00','Каждый час · В начале часа'], nextRuns:['Следующий запуск · Завтра 09:00','Следующий запуск · Понедельник 09:00','Следующий запуск · В начале часа'], run:'Запустить', running:'Проверка обновлений…', ran:'Заметки об обновлении сохранены', taskHint:'Выполняется, пока Agent в сети',
    startEyebrow:'ЛОКАЛЬНЫЙ ЗАПУСК', startTitle:'Начните на своём компьютере.', startText:'Настройте API своей модели. Запросы к внешним API отправляются соответствующему провайдеру. Для доступа с другого устройства локальный Agent должен оставаться в сети.', guide:'Быстрый старт', guideSteps:['Запустите Agent на компьютере','Подключите свои модели','Продолжайте с телефона'], guideDetails:['Войдите в приложение на компьютере и запустите локальный Agent.','Добавьте провайдера в настройках или укажите свой URL API и ключ.','Оставьте Agent на компьютере в сети и продолжайте в том же пространстве с телефона.'],
    openEyebrow:'ОТКРЫТЫЙ КОД / АРХИТЕКТУРА', openTitle:'Клиенты, Agent и сервер — отдельные проекты.', openIntro:'Agent работает на компьютере. Телефон подключается к нему через сервер, не запуская отдельный облачный Agent.', parts:['Клиенты','Локальный Agent','Сервер'], partDetails:['Интерфейсы для компьютера и телефона: диалоги, файлы, настройки моделей и темы.','Выполняет инструменты на компьютере, управляет пространством, хранит и запускает задачи по расписанию.','Предоставляет сервисы аккаунтов и связи устройств. Развёртывается отдельно, без облачного запуска моделей.'], contributeTitle:'Пользуйтесь. Помогайте развивать.', contributeText:'Воспроизводите ошибки, улучшайте документацию, создавайте темы и плагины или меняйте код. Участвуйте через issues и pull requests на GitHub.', sourceStatus:'Публичный репозиторий: kissopen/kissopen.', footer:'KissOpen · AI-пространство с открытым кодом', motion:'Анимация', motionOn:'Вкл.', motionOff:'Выкл.',
    getTitle:'Скачать KissOpen', getDesc:'Выберите устройство для работы.', macArm:'macOS · Apple Silicon', macIntel:'macOS · Intel', soon:'Публичная загрузка готовится', distribution:'Доступны macOS 0.3.2 и Windows 0.3.0 и Android 0.2.29. macOS подписана и заверена Apple; установщик Windows не имеет подписи кода. APK подписан ключом выпуска проекта и поддерживает ARM-устройства с Android 7.0 и новее. Версия iOS готовится.', web:'Открыть текущий веб-клиент ↗', close:'Закрыть', keyNote:'Это демо. Настоящий ключ API не нужен.',
    language:'Язык', mainNavigation:'Основная навигация', mobileNavigation:'Мобильная навигация', openApp:'Открыть приложение', appearanceToggle:'Переключить светлую/тёмную тему', darkMode:'Включить тёмную тему', lightMode:'Включить светлую тему', demoStages:'Этапы демонстрации', myModel:'Моя модель', changelog:'Журнал изменений', docs:'Документация', projectNotes:'Заметки проекта', extensions:'ПЛАГИНЫ / РАСШИРЕНИЯ',
  },
};
