import { renderCli } from './cli.mjs';
import { cliCopy } from './cli-copy.mjs';
import { locales, translations, downloadPath } from './locales.mjs';
import { createHash } from 'node:crypto';
import { readFileSync } from 'node:fs';

// Each page references the matching asset generation, avoiding a mix of new
// markup and a browser/CDN-cached script from the previous release.
const assetRevision=createHash('sha256').update(readFileSync(new URL('./main.js',import.meta.url))).update(readFileSync(new URL('./style.css',import.meta.url))).update(readFileSync(new URL('./cli.js',import.meta.url))).digest('hex').slice(0,12);

const copy = {
  ...translations,
  zh: {
    language:'语言', mainNavigation:'主导航', mobileNavigation:'移动导航', openApp:'打开客户端', appearanceToggle:'切换浅色／深色模式', darkMode:'切换到深色模式', lightMode:'切换到浅色模式', demoStages:'演示步骤', myModel:'我的模型', changelog:'更新日志', docs:'文档', projectNotes:'项目笔记', extensions:'插件 / 扩展功能',
    title:'KissOpen — 开源 AI 工作空间', description:'KissOpen 是一个开源 AI 工作空间项目，由桌面与移动客户端、本地 Agent 和可自部署服务端组成。接入自己的模型，使用插件、主题和本地定时任务。',
    nav:['项目','功能','本地运行'], github:'GitHub', download:'获取 KissOpen', skip:'跳到正文', menu:'打开导航',
    eyebrow:'KISSOPEN / 开源项目', hero:['开源 AI 工作空间。','本地运行，跨端连接。'], intro:'Agent 在你的电脑上运行，连接你配置的模型。桌面和手机访问同一个工作空间，代码也可以自己改。', note:'桌面与移动客户端 / 本地 Agent / 可自部署服务端', watch:'查看跨端演示', heroAction:'了解如何运行',
    demoLabel:'交互演示', demoTitle:'桌面与手机如何连接同一个 Agent。', desktop:'桌面', mobile:'手机', demoCaption:'演示内容 · 手机连接在线 Agent 后继续工作', pause:'暂停演示', play:'播放演示', replay:'重新播放',
    work:'工作', library:'资料库', plugins:'插件', tasks:'定时任务', themes:'主题', projects:'项目', project:'项目文档', conversation:'版本更新', user:'阅读项目的更新日志，整理一份升级说明。', agentReply:'我会读取更新日志、检查兼容性变化，并保存到项目目录。',
    steps:['读取更新日志','检查兼容性变化','保存 upgrade-notes.md'], file:'upgrade-notes.md', fileType:'12 KB · Markdown', connected:'Agent 已连接', browser:'浏览器', sourceTitle:'项目更新日志。', sourceSub:'新增功能、兼容性变更与迁移说明。', sourceLabels:['新增功能','兼容性变更','迁移说明'], input:'接下来一起做什么？',
    phoneConnected:'桌面 Agent 在线', phoneUser:'再加一页中文摘要。', phoneReply:'正在更新升级说明…', phoneDone:'摘要已加入，桌面同步完成。', phoneInput:'发消息给 KissOpen…',
    stageNames:['桌面发起','Agent 执行','手机接力','结果同步'], stageTitles:['桌面提交任务。','本地 Agent 执行。','手机接入同一会话。','文件在工作空间中更新。'], stageDescriptions:['在桌面发起任务，让对话、文件和工具留在一个工作空间。','读取更新日志、整理变更，把升级说明保存到项目目录。','手机打开同一段对话，查看文件，再补充一句需求。','更新后的文件回到同一个工作空间，接着往下做。'],
    shared:['同一个 Agent','同一段会话','同一个工作空间'], featureEyebrow:'功能 / CAPABILITIES', featureTitle:'模型、界面和工具，都可以配置。', featureIntro:'这些是项目目前提供的能力。下方控件可以试用，不会修改真实配置。',
    modelsTitle:'自定义模型接口', modelsText:'填入 API 地址和 Key，获取模型列表，多选或全选，自由组合。', provider:'服务商', providerName:'我的模型服务', api:'API 地址', selected:'已选择 {n} 个模型', all:'全选模型', modelDemo:'模型选择演示',
    themeTitle:'自定义主题', themeText:'切换配色、换上背景，或者用一句话，让 AI 为你制作主题。', themeNames:['暮紫','青川','暖阳','墨'], createTheme:'试试换个主题', themePrompt:'“安静一点的深色，带一点紫。”', themePreview:'主题预览',
    pluginTitle:'本地插件', pluginText:'在本地 Agent 中安装、启停和卸载插件，扩展浏览器、文档与开发工具。', pluginNames:['浏览器工具','文档工具','开发工具'], pluginCount:'{n} 项能力已启用', togglePlugin:'切换',
    taskTitle:'本地定时任务', taskText:'在对话里说清楚要做什么、什么时候做，交给本地 Agent 定时执行。', taskName:'检查项目更新', frequencies:['每天','每周','每小时'], times:['每天 · 09:00','每周一 · 09:00','每小时 · 整点'], nextRuns:['下次运行 · 明天 09:00','下次运行 · 周一 09:00','下次运行 · 下个整点'], run:'立即运行', running:'正在检查更新…', ran:'更新记录已生成', taskHint:'Agent 在线时执行',
    startEyebrow:'运行 / GET STARTED', startTitle:'先在自己的电脑上运行。', startText:'模型接口需要自行配置；使用远程接口时，请求会发送给对应服务商。跨端访问时，本地 Agent 需要保持在线。', guide:'快速上手', guideSteps:['启动桌面 Agent','接入你的模型','连接手机，继续工作'], guideDetails:['在桌面客户端登录并启动本地 Agent。','在设置中添加服务商，或填写自定义 API 地址和 Key。','让桌面 Agent 保持在线，手机使用同一工作空间继续对话。'],
    openEyebrow:'结构 / OPEN SOURCE', openTitle:'客户端、Agent、服务端，分开维护。', openIntro:'桌面是 Agent 的运行入口；手机通过服务端连接它，不是另外启动一个云端 Agent。', parts:['客户端','本地 Agent','服务端'], partDetails:['桌面与移动界面：对话、文件、模型配置和主题。','在电脑上执行工具、管理工作空间，并保存和调度定时任务。','提供账号和设备连接服务，可以独立部署；不负责云端模型推理。'], contributeTitle:'不只是使用，也可以参与。', contributeText:'复现问题、补充文档、制作主题、开发插件，或直接修改代码。通过 GitHub 提交 Issue 和 Pull Request，一起完善 KissOpen。', sourceStatus:'公开仓库：kissopen/kissopen。', footer:'KissOpen · 开源 AI 工作空间', motion:'动态效果', motionOn:'开启', motionOff:'关闭',
    getTitle:'获取 KissOpen', getDesc:'选择你要使用的设备。', macArm:'macOS · Apple 芯片', macIntel:'macOS · Intel', windows:'Windows · x64', ios:'iPhone / iPad', android:'Android', soon:'公开下载即将开放', distribution:'macOS 0.3.1 与 Windows 0.3.0、Android 0.2.29 已开放下载。macOS 已签名并通过 Apple 公证；Windows 安装包未做代码签名；Android APK 使用项目发布密钥签名，支持 Android 7.0 及以上的 ARM 设备。iOS 下载仍在准备。', web:'打开当前 Web 客户端 ↗', close:'关闭', keyNote:'这是界面演示，无需输入真实密钥。',
  },
  en: {
    language:'Language', mainNavigation:'Main navigation', mobileNavigation:'Mobile navigation', openApp:'Open app', appearanceToggle:'Toggle light / dark mode', darkMode:'Switch to dark mode', lightMode:'Switch to light mode', demoStages:'Demo stages', myModel:'My model', changelog:'Changelog', docs:'Docs', projectNotes:'Project notes', extensions:'PLUGINS / EXTENSIONS',
    title:'KissOpen — An open-source AI workspace', description:'An open-source AI workspace with desktop and mobile clients, a local Agent, and a self-hostable server. Connect your own models, plugins, themes, and local scheduled tasks.',
    nav:['Project','Features','Run locally'], github:'GitHub', download:'Get KissOpen', skip:'Skip to content', menu:'Open navigation',
    eyebrow:'KISSOPEN / OPEN SOURCE', hero:['An open-source','AI workspace.'], intro:'An Agent on your computer, connected to your models. Desktop and mobile share a workspace. Change the code to make it yours.', note:'Desktop & mobile clients / Local Agent / Self-hostable server', watch:'See the cross-device demo', heroAction:'How to run it',
    demoLabel:'INTERACTIVE DEMO', demoTitle:'Desktop and mobile, connected to the same Agent.', desktop:'Desktop', mobile:'Mobile', demoCaption:'Illustrative demo · Continue on mobile with your Agent online', pause:'Pause demo', play:'Play demo', replay:'Replay demo',
    work:'Work', library:'Library', plugins:'Plugins', tasks:'Scheduled tasks', themes:'Themes', projects:'Projects', project:'Project docs', conversation:'Release notes', user:'Read the changelog and write an upgrade guide.', agentReply:'I’ll read the changelog, check compatibility changes, and save the guide to the project.',
    steps:['Read the changelog','Check compatibility changes','Save upgrade-notes.md'], file:'upgrade-notes.md', fileType:'12 KB · Markdown', connected:'Agent connected', browser:'Browser', sourceTitle:'Project changelog.', sourceSub:'New features, compatibility changes, and migration notes.', sourceLabels:['New features','Compatibility','Migration notes'], input:'What shall we work on?',
    phoneConnected:'Desktop Agent online', phoneUser:'Add a one-page summary.', phoneReply:'Updating the guide…', phoneDone:'Summary added. Desktop is up to date.', phoneInput:'Message KissOpen…',
    stageNames:['Start on desktop','Agent at work','Continue on mobile','Back in sync'], stageTitles:['Submit a task on desktop.','The local Agent runs it.','Connect to the session on mobile.','The workspace files are updated.'], stageDescriptions:['Start a task on desktop, with your conversation, files, and tools in one workspace.','Read the changelog, review the changes, and save an upgrade guide to the project.','Open the same conversation on your phone. Read the guide and add a request.','The updated file is waiting in the same workspace. Pick up from there.'],
    shared:['One Agent','One conversation','One workspace'], featureEyebrow:'CAPABILITIES', featureTitle:'Configurable models, interfaces, and tools.', featureIntro:'What the project supports today. Try the controls below; they won’t change a real configuration.',
    modelsTitle:'Custom model endpoints', modelsText:'Connect an API URL and key. Load the model list, then choose one, many, or all.', provider:'Provider', providerName:'My model service', api:'API URL', selected:'{n} models selected', all:'Select all models', modelDemo:'Model selection demo',
    themeTitle:'Custom themes', themeText:'Switch colors and backgrounds, or describe a theme and let AI create it.', themeNames:['Dusk','River','Amber','Mono'], createTheme:'Try another theme', themePrompt:'“Quiet, dark, with a little violet.”', themePreview:'Theme preview',
    pluginTitle:'Local plugins', pluginText:'Install, enable, disable, and remove plugins in your local Agent for browsing, documents, and development.', pluginNames:['Browser tools','Document tools','Developer tools'], pluginCount:'{n} capabilities enabled', togglePlugin:'Toggle',
    taskTitle:'Local scheduled tasks', taskText:'Describe a task and its schedule in chat. Your local Agent saves and runs it.', taskName:'Check project updates', frequencies:['Daily','Weekly','Hourly'], times:['Every day · 09:00','Every Monday · 09:00','Every hour · On the hour'], nextRuns:['Next run · Tomorrow 09:00','Next run · Monday 09:00','Next run · Next hour'], run:'Run now', running:'Checking for updates…', ran:'Update notes saved', taskHint:'Runs while your Agent is online',
    startEyebrow:'RUN LOCALLY', startTitle:'Start on your own computer.', startText:'Configure your own model endpoint. Remote endpoints send requests to that provider. Keep the local Agent online for access from another device.', guide:'Quick start', guideSteps:['Start your desktop Agent','Connect your models','Pick up on your phone'], guideDetails:['Sign in to the desktop app and start your local Agent.','Add a provider in Settings, or connect a custom API URL and key.','Keep your desktop Agent online and continue in the same workspace on mobile.'],
    openEyebrow:'OPEN SOURCE / ARCHITECTURE', openTitle:'Clients, Agent, and server. Maintained separately.', openIntro:'The desktop runs the Agent. Mobile connects to it through the server, rather than starting a separate cloud Agent.', parts:['Clients','Local Agent','Server'], partDetails:['Desktop and mobile interfaces for conversations, files, model configuration, and themes.','Runs tools on your computer, manages the workspace, and stores and runs scheduled tasks.','Provides account and device connectivity services. Independently deployable, without cloud model inference.'], contributeTitle:'Use it. Help build it.', contributeText:'Reproduce bugs, improve the docs, create themes or plugins, or change the code. Join in on GitHub with issues and pull requests.', sourceStatus:'Public repository: kissopen/kissopen.', footer:'KissOpen · An open-source AI workspace', motion:'Motion', motionOn:'On', motionOff:'Off',
    getTitle:'Get KissOpen', getDesc:'Choose where you want to work.', macArm:'macOS · Apple Silicon', macIntel:'macOS · Intel', windows:'Windows · x64', ios:'iPhone / iPad', android:'Android', soon:'Public download coming soon', distribution:'macOS 0.3.1 and Windows 0.3.0 and Android 0.2.29 are available. macOS is signed and notarized by Apple; the Windows installer is not code-signed. The Android APK is signed with the project release key and supports ARM devices running Android 7.0 or later. iOS downloads are still being prepared.', web:'Open the current web client ↗', close:'Close', keyNote:'Interactive preview. No real API key needed.',
  }
};
const paths={arrow:'M7 17 17 7M7 7h10v10',right:'M5 12h14m-6-6 6 6-6 6',down:'M12 3v12m-5-5 5 5 5-5M5 17v4h14v-4',chat:'M21 11a9 9 0 0 1-9 9H3l2-5a9 9 0 1 1 16-4Z',file:'M14 2H5v20h14V7Zm0 0v6h5M8 12h8m-8 4h6',folder:'M3 6h7l2 3h9v11H3Z',grid:'M3 3h7v7H3Zm11 0h7v7h-7ZM3 14h7v7H3Zm11 0h7v7h-7Z',clock:'M12 8v5l3 2M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0Z',theme:'M12 3a9 9 0 1 0 0 18c2 0 3-1 2-3s1-3 3-3c5 0 5-12-5-12ZM7 9h.01M11 6h.01M16 8h.01M6 14h.01',cube:'m12 2 10 6v10l-10 5-10-5V8Zm0 0v10m10-4-10 4L2 8m10 4v11',globe:'M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0ZM3 12h18M12 3c-5 5-5 13 0 18 5-5 5-13 0-18Z',code:'m8 6-6 6 6 6m8-12 6 6-6 6M14 3l-4 18',check:'m5 12 4 4L19 6',phone:'M7 2h10v20H7Zm4 17h2',monitor:'M3 3h18v14H3Zm9 14v4m-5 0h10',play:'m9 5 11 7-11 7Z',pause:'M8 5v14M16 5v14',x:'m6 6 12 12M6 18 18 6',menu:'M4 6h16M4 12h16M4 18h16',spark:'m12 2 3 7 7 3-7 3-3 7-3-7-7-3 7-3Z'};
const icon=(name,cls='')=>`<svg class="icon ${cls}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="${paths[name]||paths.grid}"/></svg>`;
const esc=s=>String(s).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
const brand=(small=false)=>small?`<img src="/assets/mark.svg" alt="" class="brand-mark" width="28" height="28">`:`<span class="brand-lockup"><img src="/assets/logo.svg" alt="KissOpen" class="brand-logo logo-dark" width="196" height="28"><img src="/assets/logo-light.svg" alt="KissOpen" class="brand-logo logo-light" width="196" height="28"></span>`;
export const siteCopy = lang => copy[lang];
export { icon, esc, brand };
export function githubLink(releases, className='', label='') {
  const url = typeof releases.source==='string' && releases.source.startsWith('https://') ? releases.source : 'https://github.com/kissopen/kissopen';
  return `<a class="${className}" href="${esc(url)}" target="_blank" rel="noopener noreferrer" aria-label="GitHub · kissopen/kissopen" title="GitHub · kissopen/kissopen"><svg class="icon github-icon" viewBox="0 0 24 24" aria-hidden="true"><path d="M12 0C5.37 0 0 5.37 0 12c0 5.3 3.44 9.8 8.21 11.39.6.11.82-.26.82-.58v-2.23c-3.34.73-4.04-1.42-4.04-1.42-.55-1.39-1.33-1.76-1.33-1.76-1.09-.75.08-.73.08-.73 1.21.09 1.84 1.24 1.84 1.24 1.07 1.83 2.81 1.3 3.49.99.11-.77.42-1.3.76-1.6-2.66-.3-5.47-1.33-5.47-5.93 0-1.31.47-2.38 1.24-3.22-.12-.3-.54-1.52.12-3.17 0 0 1.01-.32 3.3 1.23a11.52 11.52 0 0 1 6 0c2.29-1.55 3.3-1.23 3.3-1.23.66 1.65.24 2.87.12 3.17.77.84 1.23 1.91 1.23 3.22 0 4.61-2.81 5.62-5.48 5.92.43.37.82 1.1.82 2.22v3.29c0 .32.22.7.83.58A12 12 0 0 0 24 12C24 5.37 18.63 0 12 0Z"/></svg>${label ? `<span>${label}</span>` : ''}</a>`;
}
export function renderHeader(lang, releases, page='home') {
const locale=locales.find(item=>item.id===lang), t=copy[lang], home=page==='download'?locale.path:'';
const appearance=`<button class="icon-button appearance-toggle" aria-label="${t.appearanceToggle}" title="${t.appearanceToggle}"><svg class="icon sun-icon" viewBox="0 0 24 24" aria-hidden="true"><circle cx="12" cy="12" r="4"/><path d="M12 2v2m0 16v2M2 12h2m16 0h2M5 5l1.5 1.5m11 11L19 19M5 19l1.5-1.5m11-11L19 5"/></svg><svg class="icon moon-icon" viewBox="0 0 24 24" aria-hidden="true"><path d="M20 15.5A9 9 0 0 1 8.5 4 9 9 0 1 0 20 15.5Z"/></svg></button>`;
const nav=t.nav.map((x,i)=>`<a href="${home}#${['product','features','start'][i]}">${x}</a>`).join('')+`<a href="${downloadPath(locale)}">${t.download}</a>`;
return `<header class="header"><a href="${locale.path}" aria-label="KissOpen">${brand()}</a><nav aria-label="${t.mainNavigation}">${nav}</nav><div class="header-actions">${githubLink(releases,'icon-button github-link')}${appearance}<a class="button button-small button-outline web-client-link" href="https://app.kissopen.com/" target="_blank" rel="noopener noreferrer">${t.openApp}${icon('arrow')}</a><button class="icon-button menu-button" aria-label="${t.menu}" aria-expanded="false" aria-controls="mobile-nav">${icon('menu')}</button></div></header><nav class="mobile-nav" id="mobile-nav" aria-label="${t.mobileNavigation}" hidden>${nav}<a href="https://app.kissopen.com/" target="_blank" rel="noopener noreferrer">${t.openApp} ↗</a>${githubLink(releases,'text-button github-link',t.github)}</nav>
`;
}
export function renderFooter(lang, releases, page='home') {
const locale=locales.find(item=>item.id===lang), t=copy[lang], home=page==='download'?locale.path:'';
return `<footer><a href="${locale.path}" aria-label="KissOpen">${brand()}</a><p>${t.footer}</p><div><button class="motion-toggle" aria-pressed="true">${t.motion}<span>${t.motionOn}</span></button><a href="${home}#start">${t.guide}</a><a href="${downloadPath(locale)}">${t.download}</a>${githubLink(releases,'text-button github-link',t.github)}</div><label class="footer-language" for="site-language">${icon('globe')}<span>${t.language}</span><select id="site-language" name="language">${locales.map(item=>`<option value="${page==='download'?downloadPath(item):item.path}" lang="${item.tag}" ${item.id===lang?'selected':''}>${item.label}</option>`).join('')}</select></label><noscript><nav class="language-fallback" aria-label="${t.language}">${locales.map(item=>`<a href="${page==='download'?downloadPath(item):item.path}" lang="${item.tag}" ${item.id===lang?'aria-current="page"':''}>${item.label}</a>`).join('')}</nav></noscript><span class="footer-domain">kissopen.com</span></footer>`;
}
export function render(lang='en', releases={}) {
const locale=locales.find(item=>item.id===lang);
if (!locale) throw new Error(`Unknown locale: ${lang}`);
const t=copy[lang];
const file=()=>`<div class="file-chip">${icon('file')}<span><b>${t.file}</b><small>${t.fileType}</small></span>${icon('right')}</div>`;
return `<!doctype html><html lang="${locale.tag}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#111215"><script>(()=>{let saved;try{saved=localStorage.getItem('kissopen-site-appearance')}catch{}const mode=saved==='light'||saved==='dark'?saved:matchMedia('(prefers-color-scheme: light)').matches?'light':'dark';document.documentElement.dataset.appearance=mode;document.querySelector('meta[name="theme-color"]').content=mode==='light'?'#f7f7fb':'#111215'})()</script><title>${t.title}</title><meta name="description" content="${t.description}"><link rel="canonical" href="https://kissopen.com${locale.path}">${locales.map(item=>`<link rel="alternate" hreflang="${item.tag}" href="https://kissopen.com${item.path}">`).join('')}<link rel="alternate" hreflang="x-default" href="https://kissopen.com/"><meta property="og:title" content="${t.title}"><meta property="og:description" content="${t.description}"><meta property="og:type" content="website"><meta property="og:url" content="https://kissopen.com${locale.path}"><meta property="og:locale" content="${locale.og}"><link rel="icon" href="/assets/favicon.ico"><link rel="stylesheet" href="/style.css?v=${assetRevision}"><script type="module" src="/main.js?v=${assetRevision}"></script><script type="module" src="/cli.js?v=${assetRevision}"></script></head><body>
<a class="skip" href="#main">${t.skip}</a><div class="page-frame">${renderHeader(lang,releases)}
<main id="main"><section class="hero" id="product"><canvas id="constellation" aria-hidden="true"></canvas><div class="hero-art-caption" aria-hidden="true">KISSOPEN / AGENT WORKSPACE<br><span>35° 00′ LOCAL / CONNECTED</span></div><div class="hero-copy"><p class="eyebrow"><span></span>${t.eyebrow}</p><h1>${t.hero[0]}<br><span>${t.hero[1]}</span></h1><p class="hero-description">${t.intro}</p>${renderCli(lang, true)}<div class="hero-actions"><a class="button button-primary" href="${downloadPath(locale)}">${t.download}${icon('down')}</a><a class="underlink" href="#demo">${t.watch}${icon('arrow')}</a></div><p class="hero-note">${t.note}</p></div></section>
<section class="demo-section" id="demo" aria-label="${t.demoTitle}"><div class="demo-toolbar"><span class="micro">${t.demoLabel}<i class="live-dot"></i></span><div><button id="replay" class="icon-button" aria-label="${t.replay}">↻</button><button id="play-pause" class="icon-button" aria-label="${t.pause}">${icon('pause')}</button></div></div><div class="devices" data-stage="0"><div class="desktop-window"><div class="window-bar"><div class="traffic"><i></i><i></i><i></i></div><span>KissOpen</span>${icon('monitor')}</div><div class="desktop-body"><aside class="app-sidebar">${[[t.work,'chat'],[t.library,'folder'],[t.plugins,'grid'],[t.tasks,'clock'],[t.themes,'theme']].map(([v,i],n)=>`<div class="sidebar-item ${n===0?'active':''}">${icon(i)}<span>${v}</span></div>`).join('')}<div class="app-project-label">${t.projects}<span>+</span></div><div class="sidebar-item">${icon('folder')}<span>${t.project}</span></div><div class="sidebar-bottom">${brand(true)}<span>KissOpen</span></div></aside><div class="conversation"><div class="pane-title">${t.conversation}<span>···</span></div><div class="chat-content"><div class="user-message"><span class="avatar">U</span><p>${t.user}</p></div><div class="assistant-message">${brand(true)}<div><b>KissOpen</b><p>${t.agentReply}</p></div></div><ol class="task-checks">${t.steps.map((s,i)=>`<li data-check="${i}"><span>${icon('check')}</span>${s}</li>`).join('')}</ol><div class="desktop-file">${file()}</div><p class="demo-success">${icon('check')}<span>${t.stageNames[3]}</span></p></div><div class="app-composer"><span>${t.input}</span><div><span class="model-chip">${t.myModel}⌄</span><span class="send-icon">${icon('right')}</span></div></div></div><div class="browser-pane"><div class="pane-title">${icon('globe')}${t.browser}<span>↔</span></div><div class="address-bar">‹ <span>⌾ example.com/research</span>↻</div><div class="research-page"><div class="research-nav"><span>${t.changelog}<span class="accent-dot">.</span></span><small>${t.docs} ↗</small></div><p class="research-eyebrow">${t.projectNotes} / 01</p><h3>${t.sourceTitle}</h3><p>${t.sourceSub}</p><div class="research-chart"><i></i><i></i><i></i><i></i><i></i><i></i></div>${t.sourceLabels.map((x,i)=>`<div class="research-row"><span>0${i+1}</span><b>${x}</b><i></i></div>`).join('')}<div class="research-lines"><i></i><i></i></div><div class="demo-cursor">${icon('arrow')}<span></span></div></div></div></div><div class="app-status"><span><i class="live-dot"></i>${t.connected}</span><span>~/KissOpen</span></div></div>
<svg class="handoff-path" viewBox="0 0 1000 600" preserveAspectRatio="none" aria-hidden="true"><path d="M480 430 C730 430 680 185 866 185" pathLength="100"/><circle r="4"><animateMotion dur="2s" repeatCount="indefinite" path="M480 430 C730 430 680 185 866 185"/></circle></svg><div class="phone"><div class="phone-island"></div><div class="phone-status"><b>9:41</b><span>▂▄▆ ▰</span></div><div class="phone-connection"><i class="live-dot"></i>${t.phoneConnected}</div><div class="phone-title">‹ <b>${t.conversation}</b><span>···</span></div><div class="phone-thread"><div class="phone-file">${file()}</div><div class="phone-request">${t.phoneUser}</div><div class="phone-response">${brand(true)}<b>KissOpen</b><p>${t.phoneReply}</p><span class="typing"><i></i><i></i><i></i></span></div></div><div class="phone-composer"><span>${t.phoneInput}</span><span class="send-icon">${icon('right')}</span></div><div class="phone-tabs">${icon('chat')}${icon('file')}${icon('grid')}<span>···</span></div><div class="phone-home"></div></div></div>
<div class="demo-story"><div class="stage-copy" aria-live="off"><h2 id="stage-title">${t.stageTitles[0]}</h2><p id="stage-description">${t.stageDescriptions[0]}</p></div><div class="stage-controls" role="group" aria-label="${t.demoStages}">${t.stageNames.map((s,i)=>`<button data-stage-button="${i}" aria-pressed="${i===0}"><span>0${i+1}</span>${s}<i></i></button>`).join('')}</div></div><p class="demo-caption">${t.demoCaption}</p><div class="capability-strip">${t.shared.map(x=>`<span>${x}</span>`).join('')}</div></section>
<section class="features section" id="features"><div class="section-heading reveal"><p class="eyebrow"><span></span>${t.featureEyebrow}</p><h2>${t.featureTitle}</h2><p>${t.featureIntro}</p></div><div class="feature-grid">
<article class="feature-card reveal models-card"><div class="feature-heading">${icon('cube')}<div><h3>${t.modelsTitle}</h3><p>${t.modelsText}</p></div><span class="feature-index">01</span></div><div class="model-demo" role="group" aria-label="${t.modelDemo}"><div class="connection-fields"><div><span>${t.provider}</span><b>${t.providerName}</b></div><div><span>${t.api}</span><code>https://api.example.com/v1</code></div><div><span>API Key</span><code>••••••••••••••••</code></div></div><div class="model-list">${['Model A','Model B','Model C'].map((v,i)=>`<label><input type="checkbox" name="models" value="${i}" ${i<2?'checked':''}><span>${v}</span></label>`).join('')}<button class="text-button" id="select-models">${t.all} ↗</button></div></div><div class="feature-foot"><span>${t.keyNote}</span><output id="model-count">${t.selected.replace('{n}','2')}</output></div></article>
<article class="feature-card reveal themes-card"><div class="feature-heading">${icon('theme')}<div><h3>${t.themeTitle}</h3><p>${t.themeText}</p></div><span class="feature-index">02</span></div><div class="theme-previews" aria-label="${t.themePreview}">${['light','dark'].map(mode=>`<div class="mini-app ${mode}"><div class="mini-top"><i></i><i></i><i></i></div><div class="mini-body"><div class="mini-sidebar">${brand(true)}<b>${t.work}</b><i></i><i></i></div><div class="mini-chat"><b>KissOpen</b><i></i><i></i><i></i><span></span></div></div></div>`).join('')}</div><div class="theme-controls"><div role="group" aria-label="${t.themes}">${t.themeNames.map((v,i)=>`<button class="swatch swatch-${i}" data-theme="${i}" aria-label="${v}" aria-pressed="${i===0}"><span>${v}</span></button>`).join('')}</div><button class="underlink" id="cycle-theme">${t.createTheme}${icon('spark')}</button></div></article>
<article class="feature-card reveal plugins-card"><div class="feature-heading">${icon('grid')}<div><h3>${t.pluginTitle}</h3><p>${t.pluginText}</p></div><span class="feature-index">03</span></div><div class="plugin-list">${t.pluginNames.map((v,i)=>`<div>${icon(['globe','file','code'][i])}<span>${v}</span><button class="switch" role="switch" aria-label="${t.togglePlugin} ${v}" aria-checked="${i<2}"><i></i></button></div>`).join('')}</div><div class="feature-foot"><span class="micro">${t.extensions}</span><output id="plugin-count">${t.pluginCount.replace('{n}','2')}</output></div></article>
<article class="feature-card reveal schedule-card"><div class="feature-heading">${icon('clock')}<div><h3>${t.taskTitle}</h3><p>${t.taskText}</p></div><span class="feature-index">04</span></div><div class="frequency-controls" role="group" aria-label="${t.tasks}">${t.frequencies.map((x,i)=>`<button data-frequency="${i}" aria-pressed="${i===1}">${x}</button>`).join('')}</div><div class="schedule-demo">${icon('file')}<div><b>${t.taskName}</b><span id="schedule-time">${t.times[1]}</span></div><button class="run-button" id="run-task">${icon('play')}<span>${t.run}</span></button></div><p class="run-result" role="status" id="run-result"></p><div class="feature-foot"><output id="next-run">${t.nextRuns[1]}</output><span>${t.taskHint}</span></div></article></div></section>
<section class="open-project section reveal" id="open-source"><div class="section-heading"><p class="eyebrow"><span></span>${t.openEyebrow}</p><h2>${t.openTitle}</h2><p>${t.openIntro}</p></div><div class="architecture">${t.parts.map((part,i)=>`<article><span class="micro">0${i+1} / ${['CLIENTS','AGENT','SERVER'][i]}</span><h3>${part}</h3><p>${t.partDetails[i]}</p></article>`).join('')}</div><div class="contributing"><div><h3>${t.contributeTitle}</h3><p>${t.contributeText}</p><small>${t.sourceStatus}</small></div>${githubLink(releases,'button button-outline github-link',t.github)}</div></section><section class="start section reveal" id="start"><div><p class="eyebrow"><span></span>${t.startEyebrow}</p><h2>${t.startTitle}</h2><p>${t.startText}</p><a class="button button-primary" href="${downloadPath(locale)}">${t.download}${icon('arrow')}</a></div><ol class="quickstart" aria-label="${t.guide}">${t.guideSteps.map((x,i)=>`<li><span>0${i+1}</span><div><h3>${x}</h3><p>${t.guideDetails[i]}</p></div></li>`).join('')}</ol></section></main>
${renderFooter(lang,releases)}</div>
<script type="application/json" id="page-copy">${JSON.stringify({...t,cliCopied:cliCopy[lang].copied,cliCopyFailed:cliCopy[lang].copyFailed}).replaceAll('<','\\u003c')}</script></body></html>`;
}
