// Code generated by cmd/kissopen-apigen from internal/api. DO NOT EDIT.
// The server's own types are the contract; change them there and regenerate.

/**
 * BillingHistoryRequest reads the current account's purchases, newest first.
 * Cursor is the last order of the preceding page; never another account's.
 */
export type BillingHistoryRequest = {
  kind: string;
  cursor?: string;
};

/** BillingOrder is a purchase, not model usage or a generated tax invoice. */
export type BillingOrder = {
  id: string;
  kind: string;
  name: string;
  days: number;
  points: number;
  amount_fen: number;
  pay_type: string;
  status: string;
  created: number;
  paid: number;
  plan_action: PlanChangeAction;
  expires_at: number;
  needs_review: boolean;
};

export type BillingHistory = {
  plan: PlanSummary;
  orders: BillingOrder[];
  next_cursor: string;
};

/** ErrorBody is what every failed request answers with. */
export type ErrorBody = {
  /** Written for the reader, in Chinese; show it as is. */
  error: string;
  /** Stable classification; ordinary failures omit it. */
  code?: string;
};

/** Ok acknowledges a request that has nothing else to say. */
export type Ok = {
  ok: boolean;
};

/** Config is what a client needs to know before anyone signs in. */
export type Config = {
  cloud_agent?: boolean;
  name: string;
  name_zh: string;
  development: boolean;
  /** No model key is configured, so replies come from a local stand-in. */
  demo_model: boolean;
  /** Phone login can deliver its code; without it there is no way to sign in. */
  sms_ready: boolean;
  /** False when no transcription model is configured, so the mic stays hidden. */
  voice_ready: boolean;
};

/** CodeRequest asks for a login code by SMS. */
export type CodeRequest = {
  phone: string;
};

/** CodeSent says a code is on its way. */
export type CodeSent = {
  ok: boolean;
  /** Seconds before another code may be asked for. */
  retry_after: number;
  /** Only in development without an SMS provider: the code itself. */
  development_code?: string;
};

/**
 * ClientKind says how a client holds its session: "web" gets an HttpOnly
 * cookie, "app" gets the token in the body as well.
 */
export type ClientKind =
  | "web"
  | "app";

/**
 * LoginRequest signs in with a phone number and the code sent to it. The
 * first sign-in with a number creates its account.
 */
export type LoginRequest = {
  phone: string;
  code: string;
  client?: ClientKind;
  /** Where a new account came from; kept only when this sign-in creates it. */
  source?: SignupSource | null;
};

/**
 * SignupSource is where a new account came from, as the client saw it on the
 * way in: the invite it followed, the campaign that brought it, the page it
 * landed on and the site that sent it, and which client it signed up with.
 */
export type SignupSource = {
  /** The invite code of the link the person arrived by. */
  ref?: string;
  utm_source?: string;
  utm_medium?: string;
  utm_campaign?: string;
  /** The first page of the site the person landed on. */
  landing?: string;
  /** The site that sent them there, when there was one. */
  referrer?: string;
  /** The client the account signed up with: web, mobile_web, desktop, ios or android. */
  client?: string;
};

/** LoginResult is a signed-in session. */
export type LoginResult = {
  ok: boolean;
  /** Present for app clients only; web clients hold the session as a cookie. */
  access_token?: string;
  /** Seconds the token is good for. */
  expires_in?: number;
};

/**
 * User is the signed-in account as the reader may see it. An account is a
 * phone number.
 */
export type User = {
  id: string;
  /** Masked, e.g. "+8613****0000". */
  phone: string;
  /**
   * The whole number, for the account's own settings to reveal on request.
   * Only ever sent to the account it belongs to.
   */
  phone_number: string;
  /** What the account calls itself; empty until it chooses a name. */
  display_name: string;
  /** Loads the avatar directly, like MessageImage.url; empty when there is none. */
  avatar_url: string;
  /**
   * What the account said about its work; null until the questionnaire is
   * answered or skipped, which is how a client knows to ask.
   */
  persona: Persona | null;
  /** The theme the account chose; null for the product's own look. */
  theme: Theme | null;
};

/** Model is a model a conversation can be answered by. */
export type Model = {
  id: string;
  name: string;
  description: string;
};

/** Conversation is one entry in the conversation list. */
export type Conversation = {
  id: string;
  user_id: string;
  title: string;
  created: number;
  updated: number;
  /** 1 when the conversation sits above the rest of the list. */
  pinned: number;
  /** 1 when the conversation is kept but out of the way. */
  archived: number;
};

/**
 * ConversationDetail is a conversation opened: its messages and, while a reply
 * is being written, the job writing it.
 */
export type ConversationDetail = Conversation & {
  /** A temporary chat: kept out of the list and erased a day after it starts. */
  temporary?: boolean;
  messages: Message[];
  /** The job still writing into this conversation, if one is. */
  job: Job | null;
};

/** ConversationUpdate changes the fields it carries and leaves the rest. */
export type ConversationUpdate = {
  title?: string | null;
  pinned?: boolean | null;
  archived?: boolean | null;
};

/** Role says who wrote a message. */
export type Role =
  | "user"
  | "assistant";

/** Status is where a job, or the message it writes, has got to. */
export type Status =
  | "queued"
  | "running"
  | "completed"
  | "failed"
  | "cancelled";

/** Message is one turn of a conversation. */
export type Message = {
  id: string;
  conversation_id: string;
  role: Role;
  /** For an assistant message still being written, what has arrived so far. */
  content: string;
  status: Status;
  created: number;
  /** The pictures this message carries, in order. */
  images: MessageImage[];
};

/** MessageImage is a picture a message carries. */
export type MessageImage = {
  id: string;
  name: string;
  mime: string;
  width: number;
  height: number;
  /**
   * Loads the picture directly, with no session needed: the address carries
   * its own permission and stays good for at least a week.
   */
  url: string;
};

/** ReasoningEffort is how hard the model should think before answering. */
export type ReasoningEffort =
  | "auto"
  | "low"
  | "medium"
  | "high";

/** ChatRequest sends a message, starting a conversation when none is named. */
export type ChatRequest = {
  /** Reused on every retry of the same send, so a retry never sends twice. */
  request_id: string;
  conversation_id?: string;
  text: string;
  /**
   * Ignored: the question decides the model. Accepted so older clients that
   * still send one are not refused.
   */
  model?: string;
  file_ids?: string[];
  image_ids?: string[];
  reasoning_effort?: ReasoningEffort;
  /** Kept out of the history and erased a day after it starts. */
  temporary?: boolean;
};

/** JobKind says what a job does. */
export type JobKind =
  | "chat";

/** Job is work the server does in the background, such as writing a reply. */
export type Job = {
  id: string;
  /** The conversation the job writes into. */
  target: string;
  kind: JobKind;
  status: Status;
  /** The last event written so far; poll for events after it. */
  seq: number;
};

/** EventKind says what a job event reports. */
export type EventKind =
  /** The job's status changed; data is a StatusEvent. */
  | "status"
  /** More reply text arrived; data is a DeltaEvent. */
  | "delta"
  /** The model started drawing a picture; data is a DrawingEvent. */
  | "drawing"
  /** A picture was attached to the reply; data is an ImageEvent. */
  | "image";

/** JobEvent is one thing that happened to a job, in order. */
export type JobEvent = {
  seq: number;
  kind: EventKind;
  /** The event's own body, JSON-encoded; its shape follows from kind. */
  data: string;
};

export type StatusEvent = {
  status: Status;
  /** Why the job stopped, written for the reader. */
  error?: string;
};

export type DeltaEvent = {
  text: string;
};

export type DrawingEvent = {
  prompt: string;
};

export type ImageEvent = {
  id: string;
};

/** EventPage is up to a hundred events after a cursor. */
export type EventPage = {
  events: JobEvent[];
  status: Status;
  /** More events wait beyond this page; ask again from the last one. */
  more: boolean;
};

/**
 * FileKind is decided by the server when a file is uploaded; every picture is
 * an image.
 */
export type FileKind =
  | "document"
  | "data"
  | "image";

/** FileUpload is a text file, sent as its content. */
export type FileUpload = {
  name: string;
  content: string;
};

/** ImageUpload is a picture, sent base64-encoded. */
export type ImageUpload = {
  name: string;
  mime: string;
  data: string;
  width: number;
  height: number;
};

/**
 * DocumentUpload is an office document — PDF, Word, Excel or PowerPoint — sent
 * base64-encoded. The server keeps the file and reads its text for the chat.
 */
export type DocumentUpload = {
  name: string;
  data: string;
};

/**
 * DocumentPDF is a document converted for viewing: the PDF, base64-encoded.
 * POST /api/documents/pdf takes a DocumentUpload and answers this.
 */
export type DocumentPDF = {
  pdf: string;
};

/** LibraryItem is a file or picture in the reader's library. */
export type LibraryItem = {
  id: string;
  name: string;
  kind: FileKind;
  /** Bytes. */
  size: number;
  created: number;
  /** The conversation it was last sent in, if any. */
  conversation_id: string | null;
  conversation_title: string | null;
  /**
   * Loads it directly, like MessageImage.url: a picture, a document as the
   * file that was uploaded, a text file as its text.
   */
  url?: string;
};

/** UploadedImage is a picture just stored. */
export type UploadedImage = {
  id: string;
  name: string;
  url: string;
};

/** TranscriptionRequest is a short recording to turn into text. */
export type TranscriptionRequest = {
  mime: string;
  /** Base64-encoded audio. */
  data: string;
  duration_ms: number;
};

export type Transcription = {
  text: string;
};

/**
 * Plan is a subscription and the limits it sets. The limits are in 分 of
 * model use; they are for proportions and are never shown as amounts.
 */
export type Plan = {
  id: string;
  name: string;
  price_fen: number;
  /**
   * Spend allowed in the last five hours, seven days and thirty days; zero
   * means that window is not enforced.
   */
  five_hour_fen: number;
  week_fen: number;
  month_fen: number;
  /** A one-time allowance, spent once and never reset. */
  grant_fen: number;
};

/** PlanSummary names a plan. */
export type PlanSummary = {
  id: string;
  name: string;
  price_fen: number;
  /** Current entitlement's end in epoch milliseconds; 0 means no expiry. */
  expires_at: number;
};

/**
 * WindowKind names a limit's window. "grant" is the one-time allowance, which
 * never resets.
 */
export type WindowKind =
  | "5h"
  | "week"
  | "month"
  | "grant";

/** UsageWindow is one limit and how far into it the account is. */
export type UsageWindow = {
  kind: WindowKind;
  /**
   * Both in micro-分. They exist to be turned into a proportion: the product
   * shows how much of a window is left and when it frees up, never a
   * quantity to watch drain.
   */
  used: number;
  limit: number;
  /**
   * The part of `used` that is only reserved: calls in flight, counted at
   * their estimated cost until they settle. Included in `used` so the
   * proportion never lags behind what is actually being spent.
   */
  reserved: number;
  /** When the window frees up; 0 while nothing has been spent into it. */
  resets_at: number;
};

/**
 * Billing is the reader's plan, how far into each of its limits they are, and
 * the plans on offer.
 */
export type Billing = {
  plan: PlanSummary;
  windows: UsageWindow[];
  plans: Plan[];
  /** What the product shows usage in. */
  points: PointsSummary;
  plan_offers: PlanChangeOffer[];
};

export type PlanChangeAction =
  | "subscribe"
  | "renew"
  | "upgrade"
  | "blocked"
  | "points";

/** A server-priced offer. Checkout recalculates it under the account lock. */
export type PlanChangeOffer = {
  id: string;
  action: PlanChangeAction;
  amount_fen: number;
  days: number;
  expires_at: number;
  message: string;
};

/** Checkout states the actual amount on the signed payment order, not a client estimate. */
export type Checkout = {
  order: string;
  url: string;
  qrcode: string;
  amount_fen: number;
  days: number;
  plan_action: PlanChangeAction;
  expires_at: number;
};

/**
 * PointsSummary is usage as the product states it: every plan grants points
 * per window, and points bought on their own are spent once the plan's window
 * is full. A point is a fixed amount of model cost (FenPerPoint 分).
 */
export type PointsSummary = {
  /** Bought or granted points not yet spent; they do not expire. */
  balance: number;
  fen_per_point: number;
  /** What can be bought. */
  packs: PointPack[];
  /** Each plan's windows, in points. */
  plans: PlanPoints[];
};

/** PointPack is an amount of points sold at a price. */
export type PointPack = {
  id: string;
  name: string;
  points: number;
  price_fen: number;
};

/** PlanPoints is one plan's windows in points; zero means not enforced. */
export type PlanPoints = {
  id: string;
  five_hour: number;
  week: number;
  month: number;
  grant: number;
};

/** Profile is what the account has done, all read from work that happened. */
export type Profile = {
  user: ProfileUser;
  plan: PlanName;
  /** Tokens in and out over the account's lifetime. */
  lifetime_in: number;
  lifetime_out: number;
  calls: number;
  /** Tokens on the busiest day of the last year. */
  peak_day: number;
  /** Consecutive active days ending today or yesterday, and the longest run. */
  current_streak: number;
  longest_streak: number;
  chats: number;
  /** Messages in the longest conversation. */
  longest_chat: number;
  images: number;
  files: number;
  /** The models used most, busiest first; at most five. */
  models: ModelUse[];
  /** One entry per day with activity in the last year, oldest first. */
  activity: ActivityDay[];
};

export type ProfileUser = {
  id: string;
  /** Masked, like User.phone. */
  phone: string;
  display_name: string;
  /** Lowercase letters, digits and underscores; empty until chosen. */
  username: string;
  avatar_url: string;
  created: number;
};

/**
 * ProfileUpdate changes the fields it carries. An empty display name or
 * username clears it.
 */
export type ProfileUpdate = {
  /** At most 40 characters. */
  display_name?: string | null;
  /** 3–20 of a–z, 0–9 and _; unique across accounts. */
  username?: string | null;
};

/**
 * AvatarUpload is a new avatar, already cropped to a square by the client and
 * sent base64-encoded.
 */
export type AvatarUpload = {
  mime: string;
  data: string;
};

export type PlanName = {
  id: string;
  name: string;
};

export type ModelUse = {
  model: string;
  runs: number;
  tokens: number;
};

export type ActivityDay = {
  /** The day in the service's time zone, as YYYY-MM-DD. */
  day: string;
  tokens: number;
};

/**
 * AgentCredentialRequest asks for a credential a device's agent can call
 * models with.
 */
export type AgentCredentialRequest = {
  name: string;
  /** How many requests the credential may make, 1–1000. */
  budget: number;
};

/**
 * AgentCredential is a device credential as listed; its token is never shown
 * again after it is created.
 */
export type AgentCredential = {
  id: string;
  name: string;
  budget: number;
  expires: number;
  revoked: number;
  created: number;
};

/** AgentCredentialCreated is a new credential, with the only copy of its token. */
export type AgentCredentialCreated = {
  id: string;
  token: string;
  expires: number;
  budget: number;
  /** An OpenAI-compatible endpoint the token works against. */
  base_url: string;
};

/** WorkspaceSession is what a client needs to reach the reader's workspace. */
export type WorkspaceSession = {
  user_id: string;
  /** Base64url; the key the workspace's content is encrypted with. */
  secret: string;
  token: string;
  server_url: string;
};

/** WorkspaceAuthorizeRequest answers a terminal's pairing request. */
export type WorkspaceAuthorizeRequest = {
  authorization: string;
};

export type WorkspaceAuthorized = {
  user_id: string;
  ok: boolean;
};

/**
 * ThemePalette is one appearance of a theme: the eleven colours every other
 * colour of the interface is derived from. Each is "#rrggbb".
 */
export type ThemePalette = {
  /** Buttons, links, selection, the brand's line. */
  accent: string;
  /** Text on the accent. */
  on_accent: string;
  /** The window behind everything. */
  canvas: string;
  /** Cards, panels, the composer. */
  surface: string;
  /** The sidebar and headers, a step away from the canvas. */
  raised: string;
  text: string;
  /** Secondary text. */
  muted: string;
  /** Hairlines and borders. */
  line: string;
  success: string;
  warning: string;
  danger: string;
};

/** ThemeBackground is a picture behind the home page and the sidebar. */
export type ThemeBackground = {
  /** Served by this API; a theme never points anywhere else. */
  url: string;
  /** How much of the picture shows through the canvas colour, 0.05–1. */
  opacity: number;
  /** Pixels of blur, 0–40. */
  blur: number;
};

/**
 * ThemeDoc is the theme itself: what a client draws, a model writes, and a
 * person exports and imports.
 */
export type ThemeDoc = {
  /** 1. */
  version: number;
  /** "sans", "serif" or "mono". */
  font: string;
  /** "sharp", "soft" or "round". */
  radius: string;
  light: ThemePalette;
  dark: ThemePalette;
  background?: ThemeBackground | null;
};

/** Theme is a theme as the product lists it. */
export type Theme = {
  id: string;
  name: string;
  description: string;
  /** "system", "ai" or "user". */
  source: string;
  /** Who made it, as others see them; empty for the product's own. */
  owner: string;
  /** The signed-in account made it. */
  mine: boolean;
  /** In the gallery for everyone. */
  public: boolean;
  featured: boolean;
  /** Accounts using it. */
  uses: number;
  created: number;
  updated: number;
  doc: ThemeDoc;
};

/**
 * ThemesPage is the theme settings page: what is chosen, what is built in,
 * what the account made, and what the gallery features.
 */
export type ThemesPage = {
  /** The chosen theme's id; empty for the product's own look. */
  selected: string;
  system: Theme[];
  mine: Theme[];
  featured: Theme[];
  /** Whether the account may ask a model for a theme right now. */
  can_generate: boolean;
};

/** ThemeGalleryRequest is a page of the gallery asked for by POST. */
export type ThemeGalleryRequest = {
  q: string;
  /** "uses" (the default) or "new". */
  sort: string;
  limit: number;
  offset: number;
};

/** ThemeGallery is a page of the themes people published. */
export type ThemeGallery = {
  themes: Theme[];
  total: number;
};

/** ThemeWrite makes or changes a theme of the account's own. */
export type ThemeWrite = {
  name: string;
  description: string;
  /** "user" for one made or imported by hand, "ai" for one a model wrote. */
  source: string;
  doc: ThemeDoc;
};

/** ThemeSelect chooses a theme for the account; an empty id is the product's own look. */
export type ThemeSelect = {
  id: string;
};

/** ThemeSelected is the account's theme after choosing; null for the product's own look. */
export type ThemeSelected = {
  theme: Theme | null;
};

/**
 * ThemeGenerateRequest asks a model for a theme from a sentence, or for a
 * change to the theme given.
 */
export type ThemeGenerateRequest = {
  prompt: string;
  base?: ThemeDoc | null;
};

/** ThemeGenerated is what the model wrote, checked and repaired; not yet saved. */
export type ThemeGenerated = {
  name: string;
  description: string;
  doc: ThemeDoc;
};

/** ThemeImageUpload is a picture for a theme's background, base64 in Data. */
export type ThemeImageUpload = {
  mime: string;
  data: string;
};

/** ThemeImage is where an uploaded picture is served from. */
export type ThemeImage = {
  url: string;
};

/**
 * AppleProduct maps a store product to a server-owned entitlement. Its price
 * must be read from StoreKit, never from the web price_fen catalog.
 */
export type AppleProduct = {
  product_id: string;
  kind: string;
  item_id: string;
  name: string;
  points: number;
};

export type AppleCatalog = {
  market: string;
  bundle_id: string;
  enabled: boolean;
  public_key: string;
  app_user_id: string;
  products: AppleProduct[];
  purchases: ApplePurchase[];
  /** Another channel has a paid term: do not sell a second subscription. */
  can_subscribe: boolean;
  subscription: AppleSubscription | null;
};

/**
 * Store receipts retain their currency, rather than pretending every price
 * is a web checkout amount in CNY. Empty price means consult the Apple receipt.
 */
export type ApplePurchase = {
  id: string;
  name: string;
  kind: string;
  points: number;
  status: string;
  purchased_at: number;
  currency: string;
  price: string;
};

export type AppleSubscription = {
  market: string;
  product_id: string;
  plan_id: string;
  expires_at: number;
  will_renew: boolean;
};

/**
 * The client names what it is waiting for, not what it deserves. Only verified
 * RevenueCat data and authenticated store notices can change entitlements.
 */
export type AppleSyncRequest = {
  market?: string;
  product_id?: string;
  transaction_id?: string;
};

export type AppleSyncResult = {
  can_subscribe: boolean;
  billing: Billing;
  /** pending means the purchase/next-cycle change has not been confirmed yet. */
  pending: boolean;
  subscription: AppleSubscription | null;
};

/** CloudWorkspace is account-owned. Runtime addresses and credentials are private. */
export type CloudWorkspace = {
  id: string;
  state: string;
  bot_id: string;
  agent_id: string;
  workspace_id: string;
  model_id: string;
  error: string;
};

/**
 * CloudProject is one project in the account's cloud workspace: a folder there
 * the workspace's agent knows as a project, with its own conversations and board.
 */
export type CloudProject = {
  id: string;
  name: string;
  /** Its folder in the cloud workspace. */
  path: string;
  /** Epoch milliseconds of its last change. */
  updated: number;
};

/** CloudProjects lists the cloud workspace's projects. */
export type CloudProjects = {
  projects: CloudProject[];
};

/**
 * CloudProjectCreate makes a project in the cloud workspace. Goal, when given,
 * is the first message of the project's first conversation.
 */
export type CloudProjectCreate = {
  /** At most 60 characters; the folder is named after it. */
  name: string;
  /** At most 4000 characters. */
  goal: string;
};

/**
 * CloudProjectCreated answers a new cloud project. AgentID is the first
 * conversation, empty when no goal was given or it could not be started; Error
 * says why in the second case, while the project itself stands.
 */
export type CloudProjectCreated = {
  project: CloudProject;
  agent_id: string;
  error?: string;
};

/**
 * Persona is what an account says about its work: the industry, the job, whether
 * it leads people, and what it wants help with. It shapes the home page and how
 * the assistant talks. A questionnaire the person skipped is a Persona with
 * Skipped set and nothing else.
 */
export type Persona = {
  /** In the person's own words, e.g. "海外电商". */
  industry: string;
  /** The job, e.g. "运营" or "行政文员". */
  occupation: string;
  /** individual, manager, owner or student; empty when not said. */
  role: string;
  /** How many people the account leads; 0 when it leads none. */
  team_size: number;
  /** What the person most wants help with, at most five. */
  goals: string[];
  skipped: boolean;
  updated: number;
};

/** PersonaUpdate replaces the account's persona whole. */
export type PersonaUpdate = {
  /** At most 30 characters. */
  industry: string;
  /** At most 30 characters. */
  occupation: string;
  /** individual, manager, owner, student or empty. */
  role: string;
  /** 0 to 10000. */
  team_size: number;
  /** At most five, each at most 20 characters. */
  goals: string[];
  skipped: boolean;
};

/**
 * HomeDemoRequest asks for the home page's demonstration data. Refresh asks
 * for new data instead of the kept one.
 */
export type HomeDemoRequest = {
  refresh: boolean;
};

/**
 * HomeDemoStatus answers a request for the home page's demonstration. A model
 * takes longer to write one than a request may wait, so the writing goes on
 * after the answer: Status is writing and Demo is null until it is done, and
 * asking again returns it.
 */
export type HomeDemoStatus = {
  /** ready or writing. */
  status: string;
  demo: HomeDemo | null;
};

/**
 * HomeDemo is the home page as it would look for this account's work: written
 * by a model from the account's persona, or from a template when no model
 * answered. Every figure in it is made up and the page says so.
 */
export type HomeDemo = {
  /** One line under the greeting, e.g. "你的海外业务，今天有了新进展。". */
  greeting: string;
  focus: HomeFocus;
  team: HomeTeam;
  projects: HomeProject[];
  forecast: HomeForecast;
  wins: HomeWins;
  /** ai when a model wrote it, template when the fallback did. */
  source: string;
  generated: number;
};

/** HomeFocus is what needs the person today. */
export type HomeFocus = {
  title: string;
  summary: string;
  items: HomeFocusItem[];
};

/** HomeFocusItem is one thing to decide or do today. */
export type HomeFocusItem = {
  title: string;
  /** box, image, doc, chart, people, calendar, mail or money. */
  icon: string;
};

/** HomeTeam is the people the person works with this week. */
export type HomeTeam = {
  title: string;
  subtitle: string;
  members: HomePerson[];
  groups: HomeGroup[];
  /** One line on who needs help, e.g. "2 位伙伴需要支持"; empty when nobody does. */
  support: string;
};

/** HomePerson is one colleague, by an invented name. */
export type HomePerson = {
  name: string;
  group: string;
};

/** HomeGroup is one part of the team and how far its week has got. */
export type HomeGroup = {
  name: string;
  count: number;
  /** 0 to 100. */
  progress: number;
};

/** HomeProject is one piece of work under way. */
export type HomeProject = {
  name: string;
  /** Where or what kind, e.g. "US · 营销活动". */
  tag: string;
  /** 0 to 100. */
  progress: number;
  /** on_track, waiting or at_risk. */
  status: string;
  /** Shown only when the status is not on_track, e.g. "待你确认". */
  status_label: string;
  /** sneakers, cup, boxes, laptop, document, chart, megaphone, calendar, bag or plant. */
  picture: string;
};

/** HomeForecast is what may happen next. */
export type HomeForecast = {
  title: string;
  subtitle: string;
  /** The headline, e.g. "+12% ~ +18%". */
  range: string;
  /** The axis unit prefix or suffix, e.g. "$" or "单". */
  unit: string;
  /** One label per point, oldest first. */
  labels: string[];
  /** Measured points, then predicted ones continuing from the last measured. */
  actual: number[];
  predicted: number[];
  note: string;
};

/** HomeWins is what went well this week. */
export type HomeWins = {
  title: string;
  /** The headline figure, e.g. "$128,400". */
  value: string;
  label: string;
  /** e.g. "+8.6%". */
  delta: string;
  metrics: HomeMetric[];
  bars: number[];
  bar_labels: string[];
  note: string;
};

/** HomeMetric is one small figure beside the headline. */
export type HomeMetric = {
  label: string;
  value: string;
};

/**
 * CloudPlugin is one package installed in the account's cloud workspace.
 *
 * Enabled and active are separate facts and stay separate: enabled is what the
 * person asked for, active is what the assistant is actually running. Between
 * the two sits a restart, and a page that showed only one of them would say a
 * plugin was on while none of its tools worked.
 */
export type CloudPlugin = {
  id: string;
  name: string;
  version: string;
  description: string;
  digest: string;
  /** What the person asked for. */
  enabled: boolean;
  /** What the assistant is running right now. */
  active: boolean;
  /** Uninstalled, and waiting for the next apply to take effect. */
  removed: boolean;
  skills: number;
  skill_root: string;
  servers: number;
  /**
   * Parts of the package this deployment will not run, named so the reader
   * knows what they are not getting rather than wondering why it is quiet.
   */
  unsupported: string[];
  format: string;
  /**
   * The servers that speak for an account the person has to connect, and
   * whether each is. A server not yet connected is left out of the
   * assistant's configuration rather than written to fail.
   */
  connections?: CloudPluginConnection[];
};

/** CloudPluginConnection is one account-backed MCP server of a plugin. */
export type CloudPluginConnection = {
  server: string;
  /**
   * The package declares this server needs an account. Others are offered
   * for connecting because they carry no credential of their own and may
   * ask for one; a public server simply never does.
   */
  required: boolean;
  /** The resource the token is minted for, as the package declares it. */
  resource: string;
  url: string;
  connected: boolean;
  /**
   * Why it is not connected, when known: an authorization the service
   * withdrew, most often.
   */
  error?: string;
};

/** CloudPluginConnectionStarted is where to send the person to approve. */
export type CloudPluginConnectionStarted = {
  authorization_url: string;
};

/** CloudPluginsList is the workspace's plugins, and what is happening to them. */
export type CloudPluginsList = {
  plugins: CloudPlugin[];
  /** A selection is being applied: the assistant is restarting onto it. */
  applying: boolean;
  /**
   * Why the last selection did not activate. It travels with the list
   * because the list is the page the person is looking at when it matters —
   * beside the switch that turns the offending plugin off.
   */
  error?: string;
};

/** CloudPluginSet turns one installed plugin on or off, or removes it. */
export type CloudPluginSet = {
  enabled: boolean;
  remove?: boolean;
};

/**
 * CloudPluginApplied acknowledges a change that needs the assistant restarted
 * before it means anything.
 */
export type CloudPluginApplied = {
  restart_required: boolean;
};

/** CloudPluginApplying acknowledges a restart onto the current selection. */
export type CloudPluginApplying = {
  applying: boolean;
};

/** CatalogPlugin is one package this deployment publishes. */
export type CatalogPlugin = {
  id: string;
  title?: string;
  version: string;
  description: string;
  skills: number;
  servers: number;
  bytes: number;
  sha256: string;
  /**
   * An absolute URL by the time a client sees it, and public: the mark
   * carries no account data and needs no credential.
   */
  icon?: string;
  /**
   * At least one of its servers wants an account connected, so those tools
   * will not work until it is.
   */
  needs_connection?: boolean;
  /**
   * And it has nothing else. Installing it before there is a way to connect
   * installs nothing that works, so it is refused rather than left broken.
   */
  connection_only?: boolean;
  /**
   * Parts this deployment cannot run, named in the listing so the decision
   * to install is made knowing them.
   */
  partial?: string[];
};

/** CatalogList is everything this deployment publishes. */
export type CatalogList = {
  plugins: CatalogPlugin[];
};

/** CatalogPackage is a verified archive for installation on the caller's computer. */
export type CatalogPackage = {
  id: string;
  sha256: string;
  archive: string;
};

/** ScheduleRecurrence is how often a schedule fires. */
export type ScheduleRecurrence =
  /** ScheduleOnce fires at one instant and then the schedule is finished. */
  | "once"
  /** ScheduleDaily fires every day at at_minute. */
  | "daily"
  /** ScheduleWeekdays fires Monday through Friday at at_minute. */
  | "weekdays"
  /** ScheduleWeekly fires on weekday at at_minute. */
  | "weekly"
  /** ScheduleInterval fires at a fixed interval, in minutes. */
  | "interval";

/**
 * ScheduleStatus is what the standing arrangement itself is doing. It is not
 * what its last run did: a recurring task that succeeded this morning is still
 * active, and one that is active is not therefore running.
 */
export type ScheduleStatus =
  | "active"
  | "paused"
  /** ScheduleEnded is a schedule the person stopped or deleted. */
  | "ended"
  /** ScheduleCompleted is a one-off that has now happened. */
  | "completed";

/**
 * ScheduleRunStatus is what became of one firing. Deliberately never
 * "delivered": handing the work over and the work happening are different
 * facts, and only the second one is worth showing as a result.
 */
export type ScheduleRunStatus =
  | "queued"
  | "waiting_device"
  | "accepted"
  | "running"
  /** ScheduleRunNeedsUser is work that stopped to ask something. */
  | "needs_user"
  | "succeeded"
  | "failed"
  | "cancelled"
  /** ScheduleRunMissed is a run whose catch-up window closed before it started. */
  | "missed"
  | "skipped";

/** ScheduleRun is one time a schedule actually fired. */
export type ScheduleRun = {
  id: string;
  schedule_id: string;
  /**
   * The instant it was meant for, which is what a reader is shown. Not when
   * the record appeared.
   */
  scheduled_for: number;
  /**
   * After this it is too late to start, and the run is missed rather than
   * run hours late.
   */
  start_before: number;
  started_at: number;
  ended_at: number;
  status: ScheduleRunStatus;
  /**
   * "pending" when the executor could not be reached to confirm this, so the
   * status is the server's last word rather than the machine's.
   */
  reconciliation: string;
  /** Non-zero once somebody asked for it to stop; stopping is not instant. */
  cancel_requested_at: number;
  /** The conversation the work happened in, so a reader can go and read it. */
  session_id: string;
  summary: string;
  error: string;
  retry_of_run_id: string;
  delivery_attempts: number;
  /**
   * When the reader looked at this result. Zero is unread, which is what a
   * badge counts; it is cleared by the reader, never by a list being shown.
   */
  read_at: number;
};

/** Schedule is a standing arrangement, distinct from any one time it ran. */
export type Schedule = {
  id: string;
  name: string;
  /**
   * Where it runs: "cloud", or "machine:<id>" — one of the account's
   * machines, by the id the relay knows it under. A machine is a legal
   * target once its desktop has reported for scheduled tasks.
   */
  target: string;
  /**
   * task follows Instruction; board has the machine's agent build the
   * project's board, from instructions the desktop there owns.
   */
  kind: ScheduleKind;
  /**
   * On a work machine, the folder the task runs in, and what that folder is
   * called there. Empty means the machine's own assistant. Nothing for the
   * cloud, which has one home.
   */
  project_path: string;
  project_name: string;
  instruction: string;
  timezone: string;
  recurrence: ScheduleRecurrence;
  /** 0-6, Sunday first. Meaningful only for a weekly schedule. */
  weekday: number;
  /** Fixed interval in minutes (1–10080), only for "interval". */
  interval_minutes?: number;
  /** Minutes past local midnight. Meaningful for daily, weekdays and weekly. */
  at_minute: number;
  /** The instant a one-off fires. Meaningful only for "once". */
  once_at: number;
  next_run_at: number;
  status: ScheduleStatus;
  catch_up_window: number;
  /** Why it is paused, when the server paused it rather than the person. */
  pause_reason: string;
  created_by: string;
  version: number;
  created: number;
  updated: number;
  /**
   * The most recent run, so a row can show both facts at once without the
   * caller asking per schedule.
   */
  last_run?: ScheduleRun | null;
};

/**
 * ScheduleMachine is one computer that can take a scheduled task.
 *
 * A machine is on this list once its desktop has reported for runs, and not
 * before: nothing is delivered to a machine — its desktop comes for the run —
 * so a task addressed to a computer that has never asked would sit queued
 * forever. Creation refuses such a target, and this is what lets the caller
 * say so while the person is still choosing rather than after they commit.
 */
export type ScheduleMachine = {
  machine_id: string;
  /** What that desktop called itself when it last reported. */
  name: string;
  /**
   * When it last asked for runs. A machine that has not asked in a while is
   * still a machine a task may be given to; it simply runs when it returns.
   */
  last_seen: number;
};

/** PushTokenRequest registers, or forgets, one device's push address. */
export type PushTokenRequest = {
  /** The token Expo gave that installation. */
  token: string;
  /**
   * "ios", "android" or whatever the device calls itself; for reading a
   * list of registered devices, never for routing.
   */
  platform?: string;
};

/** NotificationChoice is how much of what happens an account wants told to it. */
export type NotificationChoice =
  /** NotifyAll sends every finished result. */
  | "all"
  /** NotifyFailures sends only the ones that went wrong. */
  | "failures"
  /** NotifyOff sends none. Unread results are kept either way. */
  | "off";

/** NotificationSettings is what this account asked to hear about. */
export type NotificationSettings = {
  schedules: string;
};

/**
 * SchedulesList is every schedule the account has, wherever it runs, and
 * every computer of theirs a new one could be given to.
 */
export type SchedulesList = {
  /** Added by the authenticated desktop bridge; absent on HTTP clients. */
  local_machine_id?: string;
  schedules: Schedule[];
  /**
   * The account's ready machines. Absent from an older server, which the
   * caller reads as "cannot tell", not as "no machine is ready".
   */
  machines?: ScheduleMachine[];
  /**
   * Finished results nobody has looked at yet, across every schedule. It
   * rides with the list because that is the screen that shows it.
   */
  unread: number;
};

/** ScheduleDeviceOffer is the work claimed by one authenticated local computer. */
export type ScheduleDeviceOffer = {
  run_id: string;
  user_id: string;
  target: string;
  version: number;
  message_id: string;
  start_before: number;
  scheduled_for: number;
  name: string;
  instruction: string;
  kind: ScheduleKind;
  card_id?: string;
  agent_id?: string;
  project_path?: string;
  project_name?: string;
  status: ScheduleRunStatus;
  cancel_requested: boolean;
};

export type ScheduleDevicePoll = {
  runs: ScheduleDeviceOffer[];
};

/** ScheduleBody is one schedule, as read or written back. */
export type ScheduleBody = {
  schedule: Schedule;
};

/** ScheduleRunsList is the runs of one schedule, newest first. */
export type ScheduleRunsList = {
  runs: ScheduleRun[];
};

/** ScheduleCreate asks for a new schedule. */
export type ScheduleCreate = {
  interval_minutes?: number;
  target: string;
  /**
   * Absent is task. A board needs a machine target and a project folder,
   * and a project has at most one.
   */
  kind?: ScheduleKind;
  project_path?: string;
  project_name?: string;
  name: string;
  instruction: string;
  timezone: string;
  recurrence: ScheduleRecurrence;
  weekday?: number;
  at_minute?: number;
  once_at?: number;
  catch_up_window?: number | null;
  created_by?: string;
};

/**
 * ScheduleUpdate changes one schedule. Every field is optional: what is absent
 * is left alone, which is what lets a pause be a pause rather than a rewrite.
 */
export type ScheduleUpdate = {
  interval_minutes?: number | null;
  status?: ScheduleStatus | null;
  name?: string | null;
  instruction?: string | null;
  timezone?: string | null;
  recurrence?: ScheduleRecurrence | null;
  weekday?: number | null;
  at_minute?: number | null;
  once_at?: number | null;
  catch_up_window?: number | null;
  delete?: boolean;
};

/**
 * ScheduleDraftVoice is who said one line of the exchange that settles a
 * schedule.
 */
export type ScheduleDraftVoice =
  /** ScheduleDraftPerson is the person arranging the task. */
  | "person"
  /** ScheduleDraftServer is the server, which only ever asks. */
  | "server";

/** ScheduleDraftSaid is one line of that exchange. */
export type ScheduleDraftSaid = {
  who: ScheduleDraftVoice;
  text: string;
};

/**
 * ScheduleDraftRequest asks the server to read what was said as a schedule.
 *
 * `text` is the newest thing the person said and `said` is everything before
 * it, oldest first. A schedule is seldom settled in one sentence: the server
 * asks when the sentence does not say when to run, and "every night at ten"
 * means nothing without the question it answers. So the exchange travels, and
 * the reader answers where they were already typing rather than rewriting the
 * sentence they started with.
 */
export type ScheduleDraftRequest = {
  text: string;
  timezone?: string;
  said?: ScheduleDraftSaid[];
};

/**
 * ScheduleDraft is a schedule read out of a sentence but not saved. It has no
 * id, status or version because it is not a schedule yet: the caller shows it,
 * and creating it is a second request the person makes on purpose.
 */
export type ScheduleDraft = {
  interval_minutes?: number;
  name: string;
  instruction: string;
  target: string;
  timezone: string;
  recurrence: ScheduleRecurrence;
  weekday: number;
  at_minute: number;
  once_at: number;
  /**
   * When it would first fire, so the caller can show that rather than make
   * the person work it out from the rule.
   */
  next_run_at: number;
};

/**
 * ScheduleDraftBody is what came of that reading. Exactly one of the two
 * fields is present: a draft to confirm, or a question to answer first.
 */
export type ScheduleDraftBody = {
  draft?: ScheduleDraft | null;
  /**
   * What still has to be settled before this can be a schedule, in the
   * reader's own language.
   */
  needs?: string;
  /**
   * Answers worth offering beside the question, so it can be answered by
   * picking rather than typing — which is how an assistant asks anywhere
   * else in this product. Whole answers, in the reader's language ("每天
   * 09:00", not "早上"): choosing one says exactly what typing it would.
   * Empty when the question is not a choice.
   */
  choices?: string[];
};

/** ScheduleKind is what a scheduled run does. */
export type ScheduleKind =
  | "task"
  | "board";

/** ScheduleRunStarted answers a request to run a schedule now. */
export type ScheduleRunStarted = {
  run: ScheduleRun;
};
