import type { KissopenAgentProjectCatalog, KissopenAgentProjectId } from "./kissopenAgentTypes.js";

/** Recognizable world-city placeholders used until the first chat supplies a durable title. */
export const KISSOPEN_AGENT_WORKSPACE_CITY_NAMES = [
    "Tokyo",
    "London",
    "Paris",
    "New York",
    "Singapore",
    "Sydney",
    "Berlin",
    "Rome",
    "Barcelona",
    "Amsterdam",
    "Seoul",
    "Toronto",
    "Dubai",
    "Madrid",
    "Mumbai",
    "Cairo",
    "Istanbul",
    "Bangkok",
    "Mexico City",
    "Sao Paulo",
    "Buenos Aires",
    "Cape Town",
    "Nairobi",
    "Hong Kong",
    "Los Angeles",
    "San Francisco",
    "Chicago",
    "Vancouver",
    "Melbourne",
    "Lisbon",
    "Vienna",
    "Prague",
    "Athens",
    "Copenhagen",
    "Stockholm",
    "Dublin",
    "Warsaw",
    "Budapest",
    "Delhi",
    "Jakarta",
    "Manila",
    "Hanoi",
    "Auckland",
    "Rio de Janeiro",
    "Santiago",
    "Lima",
    "Bogota",
    "Casablanca",
    "Beijing",
    "Shanghai",
    "Guangzhou",
    "Shenzhen",
    "Taipei",
    "Osaka",
    "Kyoto",
    "Yokohama",
    "Nagoya",
    "Sapporo",
    "Fukuoka",
    "Busan",
    "Kuala Lumpur",
    "Ho Chi Minh City",
    "Phnom Penh",
    "Vientiane",
    "Yangon",
    "Dhaka",
    "Kolkata",
    "Bangalore",
    "Chennai",
    "Hyderabad",
    "Jaipur",
    "Karachi",
    "Lahore",
    "Islamabad",
    "Kathmandu",
    "Colombo",
    "Pune",
    "Thimphu",
    "Ulaanbaatar",
    "Macau",
    "Abu Dhabi",
    "Doha",
    "Riyadh",
    "Jeddah",
    "Muscat",
    "Kuwait City",
    "Manama",
    "Amman",
    "Beirut",
    "Jerusalem",
    "Tel Aviv",
    "Damascus",
    "Baghdad",
    "Tehran",
    "Tbilisi",
    "Yerevan",
    "Baku",
    "Astana",
    "Almaty",
    "Tashkent",
    "Samarkand",
    "Bishkek",
    "Dushanbe",
    "Ashgabat",
    "Brussels",
    "Zurich",
    "Geneva",
    "Munich",
    "Frankfurt",
    "Hamburg",
    "Cologne",
    "Milan",
    "Venice",
    "Florence",
    "Naples",
    "Turin",
    "Bologna",
    "Valencia",
    "Seville",
    "Bilbao",
    "Porto",
    "Edinburgh",
    "Manchester",
    "Liverpool",
    "Glasgow",
    "Birmingham",
    "Bristol",
    "Oslo",
    "Helsinki",
    "Reykjavik",
    "Tallinn",
    "KissopenAgenta",
    "Vilnius",
    "Krakow",
    "Gdansk",
    "Wroclaw",
    "Bucharest",
    "Sofia",
    "Belgrade",
    "Zagreb",
    "Ljubljana",
    "Sarajevo",
    "Skopje",
    "Tirana",
    "Podgorica",
    "Bratislava",
    "Salzburg",
    "Innsbruck",
    "Luxembourg",
    "Monaco",
    "Nice",
    "Lyon",
    "Marseille",
    "Bordeaux",
    "Lille",
    "Strasbourg",
    "Rotterdam",
    "The Hague",
    "Antwerp",
    "Bruges",
    "Utrecht",
    "Gothenburg",
    "Malmo",
    "Aarhus",
    "Belfast",
    "Cardiff",
    "Cambridge",
    "Oxford",
    "Lausanne",
    "Lucerne",
    "Split",
    "Dubrovnik",
    "Thessaloniki",
    "Nicosia",
    "Valletta",
    "Alexandria",
    "Giza",
    "Marrakech",
    "Rabat",
    "Fez",
    "Algiers",
    "Tunis",
    "Tripoli",
    "Dakar",
    "Accra",
    "Lagos",
    "Abuja",
    "Addis Ababa",
    "Kampala",
    "Kigali",
    "Dar es Salaam",
    "Zanzibar City",
    "Maputo",
    "Johannesburg",
    "Pretoria",
    "Durban",
    "Bloemfontein",
    "Windhoek",
    "Gaborone",
    "Lusaka",
    "Harare",
    "Antananarivo",
    "Port Louis",
    "Victoria",
    "Khartoum",
    "Mogadishu",
    "Mombasa",
    "Luanda",
    "Kinshasa",
    "Brazzaville",
    "Yaounde",
    "Douala",
    "Abidjan",
    "Boston",
    "Washington",
    "Miami",
    "Seattle",
    "Austin",
    "Houston",
    "Dallas",
    "Denver",
    "Phoenix",
    "Portland",
    "Las Vegas",
    "Atlanta",
    "New Orleans",
    "Philadelphia",
    "Montreal",
    "Ottawa",
    "Quebec City",
    "Calgary",
    "Edmonton",
    "Havana",
    "San Juan",
    "Panama City",
    "San Jose",
    "Guatemala City",
    "Santo Domingo",
    "Kingston",
    "Nassau",
    "Montego Bay",
    "Cartagena",
    "Medellin",
    "Quito",
    "Cusco",
    "La Paz",
    "Montevideo",
    "Brasilia",
    "Salvador",
    "Recife",
] as const;

export function kissopenAgentWorkspaceGeneratedName(
    catalog: KissopenAgentProjectCatalog,
    projectId: KissopenAgentProjectId,
): string {
    const usedNames = new Set(
        catalog.worktrees
            .filter((worktree) => worktree.projectId === projectId)
            .map((worktree) => worktree.name.trim().toLowerCase()),
    );
    const availableNames = KISSOPEN_AGENT_WORKSPACE_CITY_NAMES.filter(
        (name) => !usedNames.has(name.toLowerCase()),
    );
    return availableNames[Math.floor(Math.random() * availableNames.length)] ?? "Workspace";
}
