/*
 * Deterministic, offline clips for the C-236 VideoViewer specimens.
 *
 * Inline rather than fetched, for the same reason the picture specimens are:
 * the workbench must never wait on the network to take a screenshot. They are
 * VP9 in WebM because that is the one encoding all three supported engines
 * decode, and each is a few kilobytes because the content is flat colour.
 *
 * Regenerate with ffmpeg, then base64 the result:
 *
 *   wide:     -f lavfi -i "color=c=0x1f2a44:s=192x108:d=8:r=8" -c:v libvpx-vp9 -b:v 12k
 *   portrait: -f lavfi -i "color=c=0x2d1f3d:s=108x192:d=8:r=8" -c:v libvpx-vp9 -b:v 12k
 *   open:     the wide recipe written to `-f webm pipe:1`, so the segment
 *             duration is never patched back into the header and the file
 *             arrives with no length — which is what a live source looks like.
 */

function clip(base64: string): string {
    return `data:video/webm;base64,${base64}`;
}

/** 192 × 108, eight seconds: wider than most specimen frames. */
const WIDE_BASE64 =
    "GkXfo59ChoEBQveBAULygQRC84EIQoKEd2VibUKHgQJChYECGFOAZwEAAAAAAAivEU2bdLpNu4tTq4QVSalmU6yB" +
    "oU27i1OrhBZUrmtTrIHWTbuMU6uEElTDZ1OsggEjTbuMU6uEHFO7a1OsggiZ7AEAAAAAAABZAAAAAAAAAAAAAAAA" +
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
    "AAAAAAAAAAAAAAAVSalmsCrXsYMPQkBNgIxMYXZmNjIuMy4xMDBXQYxMYXZmNjIuMy4xMDBEiYhAv0AAAAAAABZU" +
    "rmvIrgEAAAAAAAA/14EBc8WIV/UH33xsvfecgQAitZyDdW5kiIEAhoVWX1ZQOYOBASPjg4QHc1lA4JCwgcC6gWya" +
    "gQJVsIRVuYEBElTDZ0B/c3OfY8CAZ8iZRaOHRU5DT0RFUkSHjExhdmY2Mi4zLjEwMHNz2mPAi2PFiFf1B998bL33" +
    "Z8ilRaOHRU5DT0RFUkSHmExhdmM2Mi4xMS4xMDAgbGlidnB4LXZwOWfIoUWjiERVUkFUSU9ORIeTMDA6MDA6MDgu" +
    "MDAwMDAwMDAwAB9DtnVEoueBAKOxgQAAgIJJg0IAC/AGtgA4JBwYUAAAcGIMQq9oAABnP//+44w+mO4xuA5A+H9s" +
    "d7ydgKOYgQB9AIYAQJKcAEoAAARg1YAAXv+lLpSAo5eBAPoAhgBAkpwAVYAAA2AAAF7/pS6UgKOXgQF3AIYAQJKc" +
    "AFCAAANgAABe/6UulICjl4EB9ACGAECSnABNAAADYAAAXv+lLpSAo5eBAnEAhgBAkpwATEAAA2AAAF7/pS6UgKOX" +
    "gQLuAIYAQJKcAEtgAANgAABe/6UulICjl4EDawCGAECSnABKYAADYAAAXv+lLpSAo5eBA+gAhgBAkpwASUAAA2AA" +
    "AF7/pS6UgKOXgQRlAIYAQJKcAEggAANgAABe/6UulICjl4EE4gCGAMCSnABEYAADYAAAXv+lLpSAo5eBBV8AhgBA" +
    "kpwAR0AAA2AAAF7/pS6UgKOXgQXcAIYAQJKcAEagAANgAABe/6UulICjl4EGWQCGAECSnABGAAADYAAAXv+lLpSA" +
    "o5eBBtYAhgBAkpwARYAAA2AAAF7/pS6UgKOXgQdTAIYAQJKcAEUgAANgAABe/6UulICjQJeBB9AAhgBAkpwARKAA" +
    "A2AAAC3////yKy////yKy////yKy///kVl/////29n/////4Lqt///5FZf///5FZf//yKy///kVl////29n////4" +
    "Lqt///5FZf///5FZf//yKy///kVl////29n////4LtWf///IrL///1YH////YHlGn///r5T///96T/////kH4JAh" +
    "JFNsC4oAo5eBCE0AhgBAkpwARMAAA2AAAF7/pS6UgKOXgQjKAIYAQJKcAEQAAANgAABe/6UulICjl4EJRwCGAECS" +
    "nABDoAADYAAAXv+lLpSAo5eBCcQAhgDAkpwAQcAAA2AAAF7/pS6UgKOXgQpBAIYAQJKcAENAAANgAABe/6UulICj" +
    "l4EKvgCGAECSnABDAAADYAAAXv+lLpSAo5eBCzsAhgBAkpwAQsAAA2AAAF7/pS6UgKOXgQu4AIYAQJKcAEKAAANg" +
    "AABe/6UulICjl4EMNQCGAECSnABCQAADYAAAXv+lLpSAo5eBDLIAhgBAkpwAQgAAA2AAAF7/pS6UgKOXgQ0vAIYA" +
    "QJKcAEHgAANgAABe/6UulICjl4ENrACGAECSnABBwAADYAAAXv+lLpSAo5eBDikAhgBAkpwAQYAAA2AAAF7/pS6U" +
    "gKOXgQ6mAIYAwJKcAEBAAANgAABe/6UulICjl4EPIwCGAECSnABBYAADYAAAXv+lLpSAo5eBD6AAhgBAkpwAQSAA" +
    "A2AAAF7/pS6UgKOZgRAdAIYAQJKcAEEAAANgAABt0WbTbjbAAKOXgRCaAIYAQJKcAEDgAANgAABe/6UulICjl4ER" +
    "FwCGAECSnABA4AADYAAAXv+lLpSAo5eBEZQAhgBAkpwAQMAAA2AAAF7/pS6UgKOXgRIRAIYAQJKcAECgAANgAABe" +
    "/6UulICjl4ESjgCGAECSnABAoAADYAAAXv+lLpSAo5eBEwsAhgBAkpwAQIAAA2AAAF7/pS6UgKOXgROIAIYAwJKc" +
    "AEAAAAIAAF780gXuwAAfQ7Z1QkPnghQFo5eBAAAAhgBAkpwAQGAAA2AAAF7/pS6UgKOXgQB9AIYAQJKcAEBgAANg" +
    "AABe/6UulICjl4EA+gCGAECSnABAQAADYAAAXv+lLpSAo5eBAXcAhgBAkpwAQEAAA2AAAF7/pS6UgKOXgQH0AIYA" +
    "QJKcAEBAAANgAABe/6UulICjl4ECcQCGAECSnABAQAADYAAAXv+lLpSAo5eBAu4AhgBAkpwAQEAAA2AAAF7/pS6U" +
    "gKOXgQNrAIYAQJKcAEBAAANgAABe/6UulICjl4ED6ACGAECSnABAQAADYAAAXv+lLpSAo5eBBGUAhgDAkpwAQAAA" +
    "AgAAXvzSBe7AAKOXgQTiAIYAQJKcAEBAAANgAABe/6UulICjl4EFXwCGAECSnABAQAADYAAAXv+lLpSAo5eBBdwA" +
    "hgBAkpwAQEAAA2AAAF7/pS6UgKOXgQZZAIYAQJKcAEBAAANgAABe/6UulICjl4EG1gCGAECSnABAQAADYAAAXv+l" +
    "LpSAo5eBB1MAhgBAkpwAQEAAA2AAAF7/pS6UgKOXgQfQAIYAQJKcAEBAAANgAABe/6UulICjl4EITQCGAECSnABA" +
    "QAADYAAAXv+lLpSAo5eBCMoAhgBAkpwAQEAAA2AAAF7/pS6UgKOXgQlHAIYAwJKcAEAAAAIAAF780gXuwACjl4EJ" +
    "xACGAECSnABAQAADYAAAXv+lLpSAo5eBCkEAhgBAkpwAQEAAA2AAAF7/pS6UgKOXgQq+AIYAQJKcAEBAAANgAABe" +
    "/6UulIAcU7trkbuPs4EAt4r3gQHxggGo8IED";

/** 108 × 192, eight seconds: letterboxed on the sides rather than above. */
const PORTRAIT_BASE64 =
    "GkXfo59ChoEBQveBAULygQRC84EIQoKEd2VibUKHgQJChYECGFOAZwEAAAAAAAgqEU2bdLpNu4tTq4QVSalmU6yB" +
    "oU27i1OrhBZUrmtTrIHWTbuMU6uEElTDZ1OsggEjTbuMU6uEHFO7a1OsgggU7AEAAAAAAABZAAAAAAAAAAAAAAAA" +
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
    "AAAAAAAAAAAAAAAVSalmsCrXsYMPQkBNgIxMYXZmNjIuMy4xMDBXQYxMYXZmNjIuMy4xMDBEiYhAv0AAAAAAABZU" +
    "rmvIrgEAAAAAAAA/14EBc8WIyjp9SjEpmx2cgQAitZyDdW5kiIEAhoVWX1ZQOYOBASPjg4QHc1lA4JCwgWy6gcCa" +
    "gQJVsIRVuYEBElTDZ0B/c3OfY8CAZ8iZRaOHRU5DT0RFUkSHjExhdmY2Mi4zLjEwMHNz2mPAi2PFiMo6fUoxKZsd" +
    "Z8ilRaOHRU5DT0RFUkSHmExhdmM2Mi4xMS4xMDAgbGlidnB4LXZwOWfIoUWjiERVUkFUSU9ORIeTMDA6MDA6MDgu" +
    "MDAwMDAwMDAwAB9DtnVEH+eBAKOygQAAgIJJg0IABrAL9gA4JBwYUAAAUGPsYAAAeTQk8///Th/7Ar25oe/7/vUc" +
    "RMZMwACjmIEAfQCGAECSnABKAAAEYNWAAGHW4dhEYKOXgQD6AIYAQJKcAFWAAANgAABh1uHYRGCjl4EBdwCGAECS" +
    "nABQgAADYAAAYdbh2ERgo5eBAfQAhgBAkpwATQAAA2AAAGHW4dhEYKOXgQJxAIYAQJKcAExAAANgAABh1uHYRGCj" +
    "l4EC7gCGAECSnABLYAADYAAAYdbh2ERgo5eBA2sAhgBAkpwASmAAA2AAAGHW4dhEYKOXgQPoAIYAQJKcAElAAANg" +
    "AABh1uHYRGCjl4EEZQCGAECSnABIIAADYAAAYdbh2ERgo5eBBOIAhgDAkpwARGAAA2AAAGHW4dhEYKOXgQVfAIYA" +
    "QJKcAEdAAANgAABh1uHYRGCjl4EF3ACGAECSnABGoAADYAAAYdbh2ERgo5eBBlkAhgBAkpwARgAAA2AAAGHW4dhE" +
    "YKOXgQbWAIYAQJKcAEWAAANgAABh1uHYRGCjl4EHUwCGAECSnABFIAADYAAAYdbh2ERgo5eBB9AAhgBAkpwARKAA" +
    "A2AAAGHW4dhEYKOXgQhNAIYAQJKcAERAAANgAABh1uHYRGCjl4EIygCGAECSnABD4AADYAAAYdbh2ERgo5eBCUcA" +
    "hgBAkpwAQ4AAA2AAAGHW4dhEYKOXgQnEAIYAwJKcAEGgAANgAABh1uHYRGCjl4EKQQCGAECSnABDQAADYAAAYdbh" +
    "2ERgo5eBCr4AhgBAkpwAQwAAA2AAAGHW4dhEYKOXgQs7AIYAQJKcAELAAANgAABh1uHYRGCjl4ELuACGAECSnABC" +
    "gAADYAAAYdbh2ERgo5eBDDUAhgBAkpwAQkAAA2AAAGHW4dhEYKOXgQyyAIYAQJKcAEIAAANgAABh1uHYRGCjl4EN" +
    "LwCGAECSnABB4AADYAAAYdbh2ERgo5eBDawAhgBAkpwAQcAAA2AAAGHW4dhEYKOXgQ4pAIYAQJKcAEGAAANgAABh" +
    "1uHYRGCjl4EOpgCGAMCSnABAQAADYAAAYdbh2ERgo5eBDyMAhgBAkpwAQWAAA2AAAGHW4dhEYKOXgQ+gAIYAQJKc" +
    "AEEgAANgAABh1uHYRGCjl4EQHQCGAECSnABBAAADYAAAYdbh2ERgo5eBEJoAhgBAkpwAQOAAA2AAAGHW4dhEYKOX" +
    "gREXAIYAQJKcAEDgAANgAABh1uHYRGCjl4ERlACGAECSnABAwAADYAAAYdbh2ERgo5eBEhEAhgBAkpwAQKAAA2AA" +
    "AGHW4dhEYKOXgRKOAIYAQJKcAECgAANgAABh1uHYRGCjl4ETCwCGAECSnABAgAADYAAAYdbh2ERgo5aBE4gAhgDA" +
    "kpwAQAAAAgAAYafp02QwH0O2dUJB54IUBaOXgQAAAIYAQJKcAEBgAANgAABh1uHYRGCjl4EAfQCGAECSnABAYAAD" +
    "YAAAYdbh2ERgo5eBAPoAhgBAkpwAQEAAA2AAAGHW4dhEYKOXgQF3AIYAQJKcAEBAAANgAABh1uHYRGCjl4EB9ACG" +
    "AECSnABAQAADYAAAYdbh2ERgo5eBAnEAhgBAkpwAQEAAA2AAAGHW4dhEYKOXgQLuAIYAQJKcAEBAAANgAABh1uHY" +
    "RGCjl4EDawCGAECSnABAQAADYAAAYdbh2ERgo5eBA+gAhgBAkpwAQEAAA2AAAGHW4dhEYKOWgQRlAIYAwJKcAEAA" +
    "AAIAAGGn6dNkMKOXgQTiAIYAQJKcAEBAAANgAABh1uHYRGCjl4EFXwCGAECSnABAQAADYAAAYdbh2ERgo5eBBdwA" +
    "hgBAkpwAQEAAA2AAAGHW4dhEYKOXgQZZAIYAQJKcAEBAAANgAABh1uHYRGCjl4EG1gCGAECSnABAQAADYAAAYdbh" +
    "2ERgo5eBB1MAhgBAkpwAQEAAA2AAAGHW4dhEYKOXgQfQAIYAQJKcAEBAAANgAABh1uHYRGCjl4EITQCGAECSnABA" +
    "QAADYAAAYdbh2ERgo5eBCMoAhgBAkpwAQEAAA2AAAGHW4dhEYKOWgQlHAIYAwJKcAEAAAAIAAGGn6dNkMKOXgQnE" +
    "AIYAQJKcAEBAAANgAABh1uHYRGCjl4EKQQCGAECSnABAQAADYAAAYdbh2ERgo5eBCr4AhgBAkpwAQEAAA2AAAGHW" +
    "4dhEYBxTu2uRu4+zgQC3iveBAfGCAajwgQM=";

/** The same picture with no length in its header, as a live source arrives. */
const OPEN_BASE64 =
    "GkXfo59ChoEBQveBAULygQRC84EIQoKEd2VibUKHgQJChYECGFOAZwH/////////EU2bdKtNu4tTq4QVSalmU6yB" +
    "oU27i1OrhBZUrmtTrIHLTbuMU6uEElTDZ1OsggEY7AEAAAAAAABoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
    "AAAAAAAAAAAAAAAVSalmpSrXsYMPQkBNgIxMYXZmNjIuMy4xMDBXQYxMYXZmNjIuMy4xMDAWVK5ryK4BAAAAAAAA" +
    "P9eBAXPFiNbXWSHvK0PSnIEAIrWcg3VuZIiBAIaFVl9WUDmDgQEj44OEB3NZQOCQsIHAuoFsmoECVbCEVbmBARJU" +
    "w2fbc3OfY8CAZ8iZRaOHRU5DT0RFUkSHjExhdmY2Mi4zLjEwMHNztmPAi2PFiNbXWSHvK0PSZ8ilRaOHRU5DT0RF" +
    "UkSHmExhdmM2Mi4xMS4xMDAgbGlidnB4LXZwOR9DtnVA/ueBAKOwgQAAgIJJg0IAC/AGtgA4JBwYUAAAUGIMQgAA" +
    "aQH//7DJX6T5t06ipXlsQwDwQlPwo5iBAH0AhgBAkpwASgAABGDVgABe/6UulICjl4EA+gCGAECSnABVgAADYAAA" +
    "Xv+lLpSAo5eBAXcAhgBAkpwAUIAAA2AAAF7/pS6UgKOXgQH0AIYAQJKcAE0AAANgAABe/6UulICjl4ECcQCGAECS" +
    "nABMQAADYAAAXv+lLpSAo5eBAu4AhgBAkpwAS2AAA2AAAF7/pS6UgKOXgQNrAIYAQJKcAEpgAANgAABe/6UulICj" +
    "l4ED6ACGAECSnABJQAADYAAAXv+lLpSAH0O2dUDl54IEZaOXgQAAAIYAQJKcAEggAANgAABe/6UulICjl4EAfQCG" +
    "AMCSnABEYAADYAAAXv+lLpSAo5eBAPoAhgBAkpwAR0AAA2AAAF7/pS6UgKOXgQF3AIYAQJKcAEagAANgAABe/6Uu" +
    "lICjl4EB9ACGAECSnABGAAADYAAAXv+lLpSAo5eBAnEAhgBAkpwARYAAA2AAAF7/pS6UgKOXgQLuAIYAQJKcAEUg" +
    "AANgAABe/6UulICjl4EDawCGAECSnABEoAADYAAAXv+lLpSAo5eBA+gAhgBAkpwAREAAA2AAAF7/pS6UgB9DtnVA" +
    "5eeCCMqjl4EAAACGAECSnABD4AADYAAAXv+lLpSAo5eBAH0AhgBAkpwAQ4AAA2AAAF7/pS6UgKOXgQD6AIYAwJKc" +
    "AEGgAANgAABe/6UulICjl4EBdwCGAECSnABDQAADYAAAXv+lLpSAo5eBAfQAhgBAkpwAQwAAA2AAAF7/pS6UgKOX" +
    "gQJxAIYAQJKcAELAAANgAABe/6UulICjl4EC7gCGAECSnABCgAADYAAAXv+lLpSAo5eBA2sAhgBAkpwAQkAAA2AA" +
    "AF7/pS6UgKOXgQPoAIYAQJKcAEIAAANgAABe/6UulIAfQ7Z1QOXngg0vo5eBAAAAhgBAkpwAQeAAA2AAAF7/pS6U" +
    "gKOXgQB9AIYAQJKcAEHAAANgAABe/6UulICjl4EA+gCGAECSnABBgAADYAAAXv+lLpSAo5eBAXcAhgDAkpwAQEAA" +
    "A2AAAF7/pS6UgKOXgQH0AIYAQJKcAEFgAANgAABe/6UulICjl4ECcQCGAECSnABBIAADYAAAXv+lLpSAo5eBAu4A" +
    "hgBAkpwAQQAAA2AAAF7/pS6UgKOXgQNrAIYAQJKcAEDgAANgAABe/6UulICjl4ED6ACGAECSnABA4AADYAAAXv+l" +
    "LpSAH0O2dUDl54IRlKOXgQAAAIYAQJKcAEDAAANgAABe/6UulICjl4EAfQCGAECSnABAoAADYAAAXv+lLpSAo5eB" +
    "APoAhgBAkpwAQKAAA2AAAF7/pS6UgKOXgQF3AIYAQJKcAECAAANgAABe/6UulICjl4EB9ACGAMCSnABAAAACAABe" +
    "/NIF7sAAo5eBAnEAhgBAkpwAQGAAA2AAAF7/pS6UgKOXgQLuAIYAQJKcAEBgAANgAABe/6UulICjl4EDawCGAECS" +
    "nABAQAADYAAAXv+lLpSAo5eBA+gAhgBAkpwAQEAAA2AAAF7/pS6UgB9DtnXP54IV+aOXgQAAAIYAQJKcAEBAAANg" +
    "AABe/6UulICjl4EAfQCGAECSnABAQAADYAAAXv+lLpSAo5eBAPoAhgBAkpwAQEAAA2AAAF7/pS6UgA==";

export const videoClipWide = clip(WIDE_BASE64);
export const videoClipPortrait = clip(PORTRAIT_BASE64);
export const videoClipOpen = clip(OPEN_BASE64);
